/**
 * lib/workers/types.ts — Shared envelope + worker-kind union.
 *
 * Every worker on the studio speaks the same protocol so the
 * generic `callWorker` helper in ./client.ts can dispatch a
 * request, await a reply by ID, and time out cleanly.
 *
 * Adding a new worker? Append its key to WorkerKind, declare
 * its file in ./registry.ts, and write a typed wrapper next to
 * the .worker.ts file. The envelope shape never changes.
 */

/**
 * The set of worker modules the studio knows about.
 *
 * Keep this list explicit (no string fallback) so a typo at a
 * `callWorker(kind, ...)` site fails at the type level rather
 * than at runtime in production.
 *
 * Note: "particle-init" lives under lib/workers/ but its
 * existing wrapper owns its own singleton with a custom message
 * protocol. It is registered here so a future migration to the
 * shared envelope can swap in without renaming the kind.
 */
export type WorkerKind =
  | "search-index"
  | "feed-parse"
  | "splat-decode"
  | "font-mesh"
  | "particle-init";

/**
 * Request envelope sent from the main thread to a worker.
 *
 * `id` is a UUID-ish string generated by the client; the worker
 * must echo it back on the matching response so we can multiplex
 * many concurrent calls over a single worker instance.
 *
 * `kind` is redundant with the worker's identity but useful for
 * debugging — every message in the devtools console says what
 * surface it belongs to.
 *
 * `op` lets one worker handle multiple verbs (e.g. the search
 * worker handles both "build" and "search").
 */
export type WorkerRequest<K extends WorkerKind, P> = {
  id: string;
  kind: K;
  op: string;
  payload: P;
};

/**
 * Response envelope sent from a worker back to the main thread.
 *
 * Either `result` (success) or `error` (failure) is set, never
 * both. Errors travel as a plain string because the structured
 * clone algorithm cannot send Error stacks reliably across all
 * browsers.
 */
export type WorkerResponse<K extends WorkerKind, R> = {
  id: string;
  kind: K;
  result?: R;
  error?: string;
};

/**
 * Helper for worker modules that want to type their own
 * incoming-message handler. Use as:
 *
 *   self.onmessage = (e: MessageEvent<AnyWorkerRequest>) => { ... };
 */
export type AnyWorkerRequest = WorkerRequest<WorkerKind, unknown>;
