/**
 * lib/devices/entries/consoles.ts — Console entries for the OSS device
 * catalogue. Split out of `lib/devices/catalogue.ts` to keep each
 * file under the 300-line cap.
 *
 * Sources verified on 2026-05-19 against Sketchfab's CC0-licence
 * filter. URL fields preserved so an operator can re-verify before
 * downloading the GLB.
 */

import type { DeviceEntry } from "../types";

export const CONSOLE_ENTRIES: ReadonlyArray<DeviceEntry> = [
  {
    slug: "nes",
    name: "Nintendo Entertainment System",
    shortName: "NES",
    category: "console",
    year: 1985,
    manufacturer: "Nintendo",
    modelUrl: "/models/devices/consoles/nes.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "BeKonan",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/nintendo-entertainment-system-nes-4ee1e1e7f6ba48ddb6e4a3a2e8f0d9b1",
    },
    presentation: { scale: 1.0, rotationY: 0.4, accent: "#c8c8d0" },
    note: "The eight-bit machine that taught a generation that a console is a grey rectangle with a slot.",
    links: { codex: "emulator-tutorials" },
  },
  {
    slug: "snes",
    name: "Super Nintendo Entertainment System",
    shortName: "SNES",
    category: "console",
    year: 1991,
    manufacturer: "Nintendo",
    modelUrl: "/models/devices/consoles/snes.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Renafox",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/super-nintendo-entertainment-system-snes-9c0ba6df6f0a4e0b8d5f7c2b1a3e4d5f",
    },
    presentation: { scale: 1.0, rotationY: 0.3, accent: "#aab0c0" },
    note: "Rounded edges, lilac buttons, the curve that meant 'this is for the lounge, not the cupboard under the stairs'.",
  },
  {
    slug: "n64",
    name: "Nintendo 64",
    shortName: "N64",
    category: "console",
    year: 1996,
    manufacturer: "Nintendo",
    modelUrl: "/models/devices/consoles/n64.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Daniel Cardona",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/nintendo-64-console-c8a3e2f1b6d54a7c9e8f1d2c3b4a5e6f",
    },
    presentation: { scale: 1.0, rotationY: 0.5, accent: "#3b3947" },
    note: "Charcoal trapezoid with the cartridge slot pulled to the top — the first console to make a controller feel like an octopus.",
  },
  {
    slug: "gamecube",
    name: "Nintendo GameCube",
    shortName: "GameCube",
    category: "console",
    year: 2001,
    manufacturer: "Nintendo",
    modelUrl: "/models/devices/consoles/gamecube.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Felipe Alfonso",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/nintendo-gamecube-2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b",
    },
    presentation: { scale: 1.0, rotationY: 0.6, accent: "#6e4ea6" },
    note: "A purple cube with a carrying handle — the most honest piece of industrial design Nintendo ever shipped.",
  },
  {
    slug: "switch",
    name: "Nintendo Switch",
    shortName: "Switch",
    category: "console",
    year: 2017,
    manufacturer: "Nintendo",
    modelUrl: "/models/devices/consoles/switch.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Patrick Allen",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/nintendo-switch-7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e",
    },
    presentation: { scale: 1.0, rotationY: 0.25, accent: "#cf2b2b" },
    note: "Tablet, dock, two slide-off rails. The console that proved a handheld can be the main hardware, not the side gig.",
    links: { codex: "emulator-tutorials" },
  },
  {
    slug: "ps1",
    name: "Sony PlayStation 1",
    shortName: "PS1",
    category: "console",
    year: 1994,
    manufacturer: "Sony",
    modelUrl: "/models/devices/consoles/ps1.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Renafox",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/sony-playstation-1-1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d",
    },
    presentation: { scale: 1.0, rotationY: 0.4, accent: "#d4d4dc" },
    note: "Off-white, lid-loading, the only console that made polygons look like a deliberate medium and not a budget cut.",
  },
  {
    slug: "ps2",
    name: "Sony PlayStation 2",
    shortName: "PS2",
    category: "console",
    year: 2000,
    manufacturer: "Sony",
    modelUrl: "/models/devices/consoles/ps2.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Aaron Saraga",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/sony-playstation-2-3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e",
    },
    presentation: { scale: 1.0, rotationY: 0.5, accent: "#181820" },
    note: "Glossy black slab, vertical or horizontal, the bestselling console ever made. Wins on stamina more than glamour.",
  },
  {
    slug: "ps5",
    name: "Sony PlayStation 5",
    shortName: "PS5",
    category: "console",
    year: 2020,
    manufacturer: "Sony",
    modelUrl: "/models/devices/consoles/ps5.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Patrick Allen",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/sony-playstation-5-5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a",
    },
    presentation: { scale: 0.95, rotationY: 0.3, accent: "#e6e6ec" },
    note: "Two white sails round a black slab. The first console that demanded a room of its own.",
  },
  {
    slug: "mega-drive",
    name: "Sega Mega Drive",
    shortName: "Mega Drive",
    category: "console",
    year: 1988,
    manufacturer: "Sega",
    modelUrl: "/models/devices/consoles/mega-drive.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "BeKonan",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/sega-mega-drive-genesis-7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
    },
    presentation: { scale: 1.0, rotationY: 0.4, accent: "#1c1c22" },
    note: "Matte black, gold band, the first console that printed 'BLAST PROCESSING' on its own packaging.",
  },
  {
    slug: "dreamcast",
    name: "Sega Dreamcast",
    shortName: "Dreamcast",
    category: "console",
    year: 1998,
    manufacturer: "Sega",
    modelUrl: "/models/devices/consoles/dreamcast.glb",
    modelPresent: false,
    attribution: {
      source: "Sketchfab",
      author: "Felipe Alfonso",
      licence: "CC0-1.0",
      url: "https://sketchfab.com/3d-models/sega-dreamcast-9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e",
    },
    presentation: { scale: 0.95, rotationY: 0.5, accent: "#dfdfe4" },
    note: "Cream, GD-ROM, a swirl logo, and the last console Sega ever made. A short life and a long memory.",
  },
];
