import Footer from "components/layout/footer";
import Link from "next/link";

export const metadata = {
  title: "Print bureau & commission terms — Holo-Flow Studio",
  description:
    "Materials, scales, finishes, quote validity, production timelines, shipping, cancellation, and the briefs the studio will not accept. Effective 14 May 2026.",
};

export default function PrintBureauTermsPage() {
  return (
    <>
      <article className="mx-auto max-w-3xl px-6 py-20 md:py-28">
        <div className="chrome-label">
          Policies &middot; Print bureau &amp; commission terms
        </div>
        <h1 className="mt-4 text-5xl md:text-6xl leading-[0.95]">
          Print bureau &amp;
          <br />
          commission terms.
        </h1>

        <p className="mt-8 max-w-xl text-chrome-200">
          The terms under which Holo-Flow Studio routes a 3D file to
          fabrication &mdash; whether through its own bench in
          Salford or through a named partner bureau. Materials,
          scales, timelines, and the briefs the studio will not
          accept.
        </p>

        <section className="mt-12 prose-gallery text-chrome-200">
          <p className="text-sm text-chrome-400">
            Effective 14 May 2026. Operator: Dimona Dougherty trading as
            Holo-Flow Studio, Salford, Greater Manchester, United
            Kingdom.
          </p>

          <h2 className="mt-12 text-2xl text-chrome-100">
            What the studio prints
          </h2>
          <p>
            Two paths run through the print bar:
          </p>
          <ul>
            <li>
              <strong>Studio Manchester</strong> &mdash; the
              studio&rsquo;s own bench. Resin and filament work in
              palm and desktop scales, finished and signed at the
              bench. The default vendor for UK orders.
            </li>
            <li>
              <strong>Partner bureaux</strong> &mdash; named drop-ship
              partners (registered at the point each contract
              lands). Used for materials and scales the bench
              doesn&rsquo;t carry &mdash; MJF nylon, sintered metal,
              shelf and wall scales. The vendor strip on the print
              bar names which partner is fulfilling a given quote.
            </li>
          </ul>
          <p>
            The studio&rsquo;s own catalogue of materials, finishes,
            and scale bands is encoded in{" "}
            <Link
              href="/stack"
              className="text-pink-200 underline underline-offset-4"
            >
              the stack
            </Link>{" "}
            and surfaced on the print bar of every relevant viewport
            on the site.
          </p>

          <h2 className="mt-12 text-2xl text-chrome-100">
            Materials, scales, and finishes
          </h2>
          <p>
            The print bar exposes the current material/scale/finish
            grid live, with the price calculated against the
            geometry the visitor is looking at. The headline
            options:
          </p>
          <ul>
            <li>
              <strong>Materials</strong> &mdash; resin (grey or
              clear), filament PLA (white), MJF nylon, stainless
              steel, sintered bronze.
            </li>
            <li>
              <strong>Scale bands</strong> &mdash; palm
              (longest edge up to about 60 mm), desktop (to about
              150 mm), shelf (to about 300 mm), wall (above 300
              mm).
            </li>
            <li>
              <strong>Finishes</strong> &mdash; raw, sanded,
              polished, painted. Not every finish is available on
              every material; the bar disables the combinations
              the vendor doesn&rsquo;t support and names the
              reason.
            </li>
          </ul>

          <h2 className="mt-12 text-2xl text-chrome-100">
            Quote validity
          </h2>
          <p>
            Quotes generated by the print bar are valid for{" "}
            <strong>fourteen days</strong> from the timestamp on
            the quote. After that, the underlying vendor pricing
            may have moved and the bar will regenerate. A quote
            converted to an order within its validity window is
            honoured at the quoted price.
          </p>
          <p>
            Bespoke commission quotes &mdash; anything routed
            through{" "}
            <a
              href="mailto:contact@holoflow.co.uk"
              className="text-pink-200 underline underline-offset-4"
            >
              contact@holoflow.co.uk
            </a>{" "}
            rather than the print bar &mdash; carry their own
            validity window, named in the quote email. Thirty days
            is the studio&rsquo;s default.
          </p>

          <h2 className="mt-12 text-2xl text-chrome-100">
            Production timelines
          </h2>
          <p>
            Indicative production windows, before shipping:
          </p>
          <ul>
            <li>
              <strong>Studio Manchester</strong> &mdash; three to
              ten working days, depending on material, scale, and
              what is ahead of the order on the bench.
            </li>
            <li>
              <strong>Partner bureaux</strong> &mdash; five to
              fifteen working days, set by the partner; the bar
              names the partner&rsquo;s own estimate at quote time.
            </li>
            <li>
              <strong>Bespoke commissions</strong> &mdash; quoted
              per brief. Anything that requires the studio to
              generate the geometry from scratch carries its own
              design window, which is named in the contract before
              the build window starts.
            </li>
          </ul>
          <p>
            These are estimates, not promises. The studio updates
            the buyer by email when a piece slips, and offers a
            cancellation route if a slip exceeds the original
            window by more than a third.
          </p>

          <h2 className="mt-12 text-2xl text-chrome-100">
            Shipping
          </h2>
          <ul>
            <li>
              <strong>United Kingdom</strong> &mdash; tracked
              courier, one to three working days from dispatch.
              Default for orders billed to a UK address.
            </li>
            <li>
              <strong>European Union</strong> &mdash; tracked
              international courier, three to seven working days
              from dispatch. The buyer is responsible for any
              import duty or VAT the destination country imposes
              on delivery.
            </li>
            <li>
              <strong>Rest of world</strong> &mdash; tracked
              international courier, five to fourteen working
              days from dispatch. Import duty and tax remain with
              the buyer.
            </li>
          </ul>
          <p>
            Larger pieces (shelf and wall scales) may ship from
            the partner bureau rather than from Salford; the
            shipping origin is named on the order confirmation.
          </p>

          <h2 className="mt-12 text-2xl text-chrome-100">
            Cancellation and refunds
          </h2>
          <ul>
            <li>
              An order may be cancelled at no charge before the
              studio or partner has started the print &mdash;
              typically within twenty-four hours of payment for
              studio orders, sooner for partner-bureau orders.
            </li>
            <li>
              Once the print is on the machine, cancellation is
              no longer possible; the order proceeds and ships
              as quoted.
            </li>
            <li>
              If a piece arrives damaged, the studio replaces or
              refunds at the buyer&rsquo;s choice, with the
              damaged piece either returned or recorded by
              photograph for the vendor claim.
            </li>
            <li>
              Statutory consumer rights under the United Kingdom
              Consumer Rights Act 2015 are unaffected.
            </li>
          </ul>

          <h2 className="mt-12 text-2xl text-chrome-100">
            Briefs the studio will not accept
          </h2>
          <p>
            The studio declines the following work, regardless of
            budget. The list is shaped by the studio&rsquo;s
            ethical position rather than by capacity:
          </p>
          <ul>
            <li>
              Invented likenesses &mdash; sculpture or print of
              an identifiable person without that person&rsquo;s
              consent. This includes deepfake-style geometry,
              celebrity facsimiles, and unsanctioned ex-partner
              imagery.
            </li>
            <li>
              Scaled-up surveillance imagery &mdash; reproductions
              of footage drawn from CCTV, doorbell cameras, or
              other surveillance feeds where the subject did not
              consent to the capture.
            </li>
            <li>
              Weapons facsimiles &mdash; functional or
              decorative reproductions of firearms, knives
              configured to UK-illegal specification, or any
              object designed to be mistaken for a weapon.
            </li>
            <li>
              Hate iconography &mdash; insignia and symbols
              associated with movements that target people on
              the basis of race, religion, sexuality, gender, or
              disability.
            </li>
            <li>
              Child-endangering content &mdash; any piece
              depicting or designed to facilitate harm to
              children.
            </li>
            <li>
              Reproductions of copyrighted designs the
              requesting party does not hold rights to &mdash;
              including unlicensed character merchandise and
              third-party brand assets.
            </li>
          </ul>
          <p>
            Where a brief sits in the grey, the studio replies
            with a clarifying question rather than a refusal.
            Where the answer to the question keeps the brief
            inside the lines above, the studio declines in
            writing and refunds any deposit already taken.
          </p>

          <h2 className="mt-12 text-2xl text-chrome-100">
            Changes to these terms
          </h2>
          <p>
            Material changes are dated at the top of the page.
            Earlier versions are kept in the site&rsquo;s git
            history and are available on request.
          </p>

          <h2 className="mt-12 text-2xl text-chrome-100">Contact</h2>
          <p>
            Bureau enquiries, bespoke briefs, and questions about a
            specific quote go to{" "}
            <a
              href="mailto:contact@holoflow.co.uk"
              className="text-pink-200 underline underline-offset-4"
            >
              contact@holoflow.co.uk
            </a>
            . Holo-Flow Studio &mdash; Salford, Greater Manchester,
            United Kingdom.
          </p>

          <p className="mt-12 text-sm text-chrome-400">
            Filed 14 May 2026. Holo-Flow Studio. See also{" "}
            <Link
              href="/policies/privacy"
              className="text-pink-200 underline underline-offset-4"
            >
              privacy
            </Link>{" "}
            and{" "}
            <Link
              href="/policies/terms"
              className="text-pink-200 underline underline-offset-4"
            >
              terms of service
            </Link>
            .
          </p>
        </section>
      </article>
      <Footer />
    </>
  );
}
