import Link from "next/link";

import { buildInstructable } from "lib/tutorials/build";
import type { Entry } from "lib/writing";

const lk = "underline underline-offset-4 hover:text-pink-200";

const SLUG =
  "blender-tutorial-python-numpy-hopf-fibration-s3-s2-quaternion-villarceau-circles-stereographic-poi-webxr";

const TITLE =
  "Python numpy — Hopf Fibration S³→S²: Quaternion h(q)=qi̅q* " +
  "Great Circles in S³ Stereographic Villarceau Rings on Clifford Tori " +
  "Hopf Link Topology N_BASE=16 N_PTS=64 Bishop Parallel-Transport Tube " +
  "Basis(Fibonacci S²)/SK_CapN(northern cap)/SK_Equat(one Clifford torus)/" +
  "SK_2Lat(two linked tori) Shape Keys Cobalt–Amber Hopf_Z FLOAT_COLOR " +
  "Poi Head for WebXR (Blender 5.1)";

const LEDE =
  "Heinz Hopf's 1931 paper proved that the 3-sphere cannot be continuously " +
  "decomposed as a product S²×S¹ — it fibres instead, each fibre being a great " +
  "circle in S³, any two of which form an inextricable Hopf link in ℝ³ after " +
  "stereographic projection.  This blueprint samples 16 Hopf fibres via the " +
  "quaternion conjugation map h(q)=qi̅q*, projects them to Villarceau circles in " +
  "ordinary space, and dresses each circle in a Bishop parallel-transport tube.  " +
  "Four shape keys walk from a Fibonacci-distributed bouquet of rings to a " +
  "single Clifford torus and then to two mutually-linked tori.";

function Body() {
  return (
    <>
      <p>
        In 1931 Heinz Hopf was studying continuous maps from spheres to spheres
        of lower dimension, asking: does every such map carry every point of the
        target to the same single point?  The answer turned out to be emphatically
        no.  The Hopf fibration h: S³→S² sends every point on the 3-sphere to a
        point on the 2-sphere, but it does so in a pattern whose fibres — the
        pre-images h⁻¹(p) — wind endlessly around each other.
      </p>
      <p>
        The discovery was a turning point in topology.  Before Hopf, all known
        maps between spheres of different dimension were homotopically trivial
        (contractible to a constant map).  The Hopf fibration showed that the
        third homotopy group of S², written π₃(S²), is non-trivial — in fact
        it is ℤ, generated by h itself.  Every integer n corresponds to a distinct
        homotopy class, and the fibration with n=1 is what we build here.
      </p>

      <h2>The Hopf map in quaternion form</h2>
      <p>
        Identify ℝ⁴ with the quaternions ℍ.  Then S³ = &#123;q ∈ ℍ : |q|=1&#125; and
        S² = &#123;p ∈ Im(ℍ) : |p|=1&#125; (the unit purely imaginary quaternions).
        The Hopf map is conjugation by the imaginary unit i:
      </p>
      <pre className="overflow-x-auto rounded bg-black/30 p-3 text-sm">
        {`h(q) = q · i · q*      (quaternion product, q* is the quaternion conjugate)

In component form (q = a + bi + cj + dk):
    h(a,b,c,d) = (2(ac+bd),  2(bc−ad),  a²+b²−c²−d²)

Verify |h(q)|² = 1 for any |q|=1:
    |2(ac+bd)|² + |2(bc−ad)|² + |a²+b²−c²−d²|²
    = 4(a²c²+2abcd+b²d²) + 4(b²c²−2abcd+a²d²) + (a²+b²−c²−d²)²
    = 4(a²+b²)(c²+d²) + (a²+b²−c²−d²)²
    = ((a²+b²)+(c²+d²))² = 1    when a²+b²+c²+d²=1  ✓`}
      </pre>
      <p>
        The kernel of h at the Lie-group level is the circle &#123;e^&#123;iθ&#125;&#125; ⊂ S³, because
        (q·e^&#123;iθ&#125;)·i·(q·e^&#123;iθ&#125;)* = q·(e^&#123;iθ&#125;·i·e^&#123;−iθ&#125;)·q* = q·i·q* = h(q).
        This confirms the fibre is S¹: multiplying q by any unit complex number
        (in the i-plane) does not change h(q).
      </p>

      <h2>Fibre parameterisation</h2>
      <p>
        Given a target point p=(px,py,pz) ∈ S², the Hopf fibre h⁻¹(p) is the
        great circle in S³ parameterised by:
      </p>
      <pre className="overflow-x-auto rounded bg-black/30 p-3 text-sm">
        {`η = arccos(√((1+pz)/2))      colatitude on S³;  η ∈ [0, π/2]
ψ = arctan2(py,px)/2           half-azimuth;      ψ ∈ [−π/2, π/2]

q(t) = (cos(η)·cos(t),
        cos(η)·sin(t),
        sin(η)·cos(ψ+t),
        sin(η)·sin(ψ+t))        for t ∈ [0, 2π)

Check:  h(q(t)) = (sin(2η)·cos(ψ),  sin(2η)·sin(ψ),  cos(2η))
                = (√(1−pz²)·cos(arg p),  √(1−pz²)·sin(arg p),  pz)  = p  for all t ✓`}
      </pre>
      <p>
        The split η/ψ decomposition comes from writing S³ as the join S¹ ★ S¹:
        η controls the ratio between two S¹ factors, while ψ and t parameterise
        each factor independently.  The Hopf map projects away the t-fibre and
        retains η and ψ as spherical coordinates on S².
      </p>

      <h2>Stereographic projection and Villarceau circles</h2>
      <p>
        Project from the north pole n=(0,0,0,1) of S³ onto the tangent hyperplane d=0:
      </p>
      <pre className="overflow-x-auto rounded bg-black/30 p-3 text-sm">
        {`π(a,b,c,d) = (a/(1−d),  b/(1−d),  c/(1−d))

Inverse:  π⁻¹(X,Y,Z) = (2X, 2Y, 2Z, R²−1) / (R²+1)   where R²=X²+Y²+Z²`}
      </pre>
      <p>
        Because π maps great circles (not through n) to circles in ℝ³, each
        Hopf fibre becomes a circle in ordinary space.  These projected circles
        are the Villarceau circles of the tori they lie on.  Every torus in ℝ³
        has four families of circles: the obvious meridional and longitudinal
        ones, and two families of Villarceau circles running diagonally — it is
        the Villarceau circles that are Hopf fibres.
      </p>
      <p>
        The south pole of S³ (n&apos;=(0,0,0,−1)) projects to the origin of ℝ³.
        The north pole n=(0,0,0,1) is the projection singularity: fibres over
        the south pole of S² approach d→1 and blow up.  The Z_MARGIN parameter
        in the blueprint excludes a 10° band around the south pole of S² to
        prevent numerically large projected circles.
      </p>

      <h2>Hopf link topology</h2>
      <p>
        Any two distinct Hopf fibres h⁻¹(p) and h⁻¹(q) are either disjoint
        (when p≠q) or they are the same circle (when p=q).  When disjoint,
        their linking number is exactly 1: you cannot separate them by a
        continuous deformation without cutting.
      </p>
      <pre className="overflow-x-auto rounded bg-black/30 p-3 text-sm">
        {`Linking number lk(γ₁, γ₂):
    lk = (1/4π) ∬ (γ₁−γ₂)/|γ₁−γ₂|³ · (dγ₁ × dγ₂)

For any two Hopf fibres: lk = 1 (regardless of which two points on S² chosen).
This is why the fibration is non-trivial: you cannot unlink them globally.`}
      </pre>

      <h2>Shape keys — four topological views</h2>
      <pre className="overflow-x-auto rounded bg-black/30 p-3 text-sm">
        {`Basis      16 fibres, Fibonacci golden-angle spiral on S²
           → distributed rings, visually like a tangled coral cage

SK_CapN    16 fibres, all base points mirrored to northern hemisphere (pz>0)
           → fibres grow progressively larger approaching the equator;
             illustrates how the projection stretches rings radially

SK_Equat   16 fibres, all base points near equator (pz≈0)
           → all rings lie on a single Clifford torus (the Villarceau family);
             reveals the √2:1 aspect ratio of the stereographic Clifford torus

SK_2Lat    8+8 fibres, two latitude circles at pz=+0.5 and pz=−0.5
           → two complete tori, each a pre-image of one latitude circle;
             they are geometrically linked — every circle on one passes through
             every circle on the other`}
      </pre>

      <h2>Bishop frame and the tube</h2>
      <p>
        A naive Frenet frame fails here: Hopf circles project to circles in ℝ³
        only generically; near the stereographic expansion region (large |π(q)|),
        the curvature of the sampled polygon can pass through zero between
        sample points, causing the Frenet normal to flip by π.  Bishop
        parallel-transport accumulates no unnecessary twist and handles
        near-zero-curvature segments gracefully.
      </p>

      <h2>Hopf_Z colour attribute</h2>
      <p>
        Each vertex carries the Z-coordinate of its position in ℝ³, mapped to
        a cobalt (negative Z, large outer rings) → amber (positive Z, small inner
        rings) gradient.  This reveals the nested structure of the Clifford tori:
        the tori closest to the north pole of the projection are smallest and
        amber; those near the equator are largest and cobalt.
      </p>

      <h2>Troubleshooting</h2>
      <ul className="list-disc pl-6 space-y-1">
        <li>
          <strong>Very large rings appear and dominate the view</strong>: a base
          point is too close to the south pole (pz≈−1), pushing the fibre near
          the projection singularity.  Increase <code>Z_MARGIN</code> from 0.10
          to 0.15 to widen the exclusion band.
        </li>
        <li>
          <strong>Tube intersects itself on SK_Equat</strong>: equatorial fibres
          project to large-radius circles and overlap at the given
          <code>TUBE_R</code>.  Reduce <code>TUBE_R</code> from 0.045 to 0.025.
        </li>
        <li>
          <strong>Script takes &gt;30 seconds</strong>: this is expected for 4
          configurations × 16 fibres × 64 × 8 = 32 768 vertices.  If you need
          speed, reduce <code>N_PTS</code> to 32 and <code>TUBE_SEGS</code> to 6.
        </li>
        <li>
          <strong>Shape key positions appear identical</strong>: confirm that each
          config function (cfg_cap_north, cfg_equatorial, cfg_two_lat) produces
          the same vertex count as cfg_basis: N_BASE × N_PTS × TUBE_SEGS.
        </li>
      </ul>

      <h2>Cross-references</h2>
      <ul className="list-disc pl-6 space-y-1">
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-torus-knot-pq-seifert-genus-milnor-fibre-bishop-tube-poi-webxr"
            className={lk}
          >
            Torus Knot T(p,q)
          </Link>{" "}
          — knots on tori are intimately related to Hopf fibres: the torus knot
          T(p,q) lies on a Clifford torus and its linking number with a Hopf
          fibre determines the knot type
        </li>
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-schwarzschild-geodesics-gr-effective-potential-isco-mercury-precession-poi-disc-webxr"
            className={lk}
          >
            Schwarzschild Geodesics
          </Link>{" "}
          — another tutorial where curves on S² drive a 3D construction; the
          base space is the same S² but the fibre structure is Riemannian rather
          than topological
        </li>
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-halton-sequence-fibonacci-sphere-lattice-scatter-poi-webxr"
            className={lk}
          >
            Fibonacci Sphere Scatter
          </Link>{" "}
          — the same golden-angle Fibonacci spiral used here to equidistribute
          base points on S²; compare the distribution geometry
        </li>
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-genesio-tesi-attractor-1992-jerk-chaos-quadratic-rk4-bishop-tube-poi-webxr"
            className={lk}
          >
            Genesio–Tesi Attractor
          </Link>{" "}
          — same Bishop parallel-transport tube construction; compare how the
          frame propagation handles a chaotic open curve versus a closed Hopf circle
        </li>
      </ul>

      <h2>Outside sources</h2>
      <ul className="list-disc pl-6 space-y-1">
        <li>
          <strong>Primary paper:</strong>{" "}
          <a
            href="https://doi.org/10.1007/BF01457962"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            Hopf, H. (1931). "Über die Abbildungen der dreidimensionalen Sphäre
            auf die Kugelfläche." <em>Mathematische Annalen</em> 104:637–665.
          </a>{" "}
          Mathematical equations are public domain as scientific facts.
          Published in{" "}
          <a
            href="https://www.springer.com/journal/208"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            Mathematische Annalen (Springer)
          </a>
          , the foremost German pure-mathematics journal; Hopf&apos;s paper is
          considered one of the founding documents of algebraic topology.
          Related contemporary work: Seifert &amp; Threlfall (1934)
          <em>Lehrbuch der Topologie</em>, which systematised much of the
          homotopy theory that Hopf pioneered.
        </li>
        <li>
          <strong>Introductory reference (openly accessible):</strong>{" "}
          <a
            href="https://faculty.lvc.edu/lyons/pubs/hopf.pdf"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            Lyons, D.W. (2003). "An Elementary Introduction to the Hopf
            Fibration." <em>Mathematics Magazine</em> 76(2):87–98.
          </a>{" "}
          — A coordinate-level proof accessible to undergraduates; derives the
          fibre parameterisation used in this blueprint.  Mathematics Magazine
          is published by the{" "}
          <a
            href="https://www.maa.org/"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            Mathematical Association of America
          </a>
          ; related sibling exposition: Urbantke H.K. (2003)
          &quot;The Hopf fibration — seven times in physics,&quot;
          <em>J. Geom. Phys.</em> 46:125–150, cataloguing its appearances
          across quantum mechanics, special relativity, and gauge theory.
        </li>
        <li>
          <strong>NumPy (BSD-3-Clause):</strong>{" "}
          <a
            href="https://numpy.org"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            numpy.org
          </a>{" "}
          — vectorised quaternion arithmetic, golden-angle spiral generation,
          and Bishop frame propagation.  Repository:{" "}
          <a
            href="https://github.com/numpy/numpy"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            github.com/numpy/numpy
          </a>
          .
        </li>
      </ul>
    </>
  );
}

const instructable = buildInstructable({
  libSlug:
    "python-numpy-hopf-fibration-s3-s2-quaternion-villarceau-circles-stereographic-poi-webxr",
  topic: "scripting",
  blenderVersion: "5.1",
  licence: "CC0",
  files: ["blueprint.py", "record.py", "SCREEN-RECORDING-NOTES.md"],
});

export const entry: Entry = {
  slug: SLUG,
  title: TITLE,
  lede: LEDE,
  date: "2026-09-02",
  tags: [
    "blender",
    "python",
    "numpy",
    "scripting",
    "topology",
    "hopf-fibration",
    "quaternion",
    "s3",
    "s2",
    "villarceau",
    "clifford-torus",
    "stereographic",
    "bishop-tube",
    "poi",
    "webxr",
  ],
  body: Body,
  instructable,
};

export const blenderTutorialPythonNumpyHopfFibrationS3S2QuaternionVillarceauCirclesStereographicPoiWebxrEntry =
  entry;
