import Link from "next/link";

import { buildInstructable } from "lib/tutorials/build";
import type { Entry } from "lib/writing";

const lk = "underline underline-offset-4 hover:text-pink-200";

const SLUG =
  "blender-tutorial-python-numpy-apollonian-circle-packing-soddy-descartes-stage-floor-webxr";

const TITLE =
  "Python — Apollonian Circle Packing: Descartes' Theorem, Soddy Integer Gasket & Bas-Relief Stage Floor for WebXR (Blender 5.1)";

const LEDE =
  "The Apollonian circle packing is the unique fractal generated by iteratively filling every gap between three mutually tangent circles with the largest circle that fits — the Apollonius circle tangent to all three. Descartes' theorem (1643) gives the curvature of this circle in closed form: k4 = k1+k2+k3 ± 2√(k1·k2+k2·k3+k3·k1). Extending this to the complex plane gives the centre simultaneously. The elegant 'mirror' recursion k_new = 2(k2+k3+k4) − k1 avoids the square root entirely and preserves integer curvatures throughout the packing (Sarnak 2007). This tutorial implements the BFS Apollonian engine in pure Python, converts the result to bas-relief cylinders (height ∝ log curvature) in a single BMesh pass, flat-shades with emission-colour ranking, and exports a Draco-6 GLB stage floor for WebXR.";

function Body() {
  return (
    <>
      <p>
        Every gap between three mutually tangent circles contains exactly one
        circle tangent to all three — the inner Apollonius circle. Fill that
        gap, and each of the four new sub-gaps contains another, and so on,
        forever. The limiting set — the{" "}
        <em>residual set</em> left after removing all the circle interiors — has
        Hausdorff dimension ≈ 1.3057 (Boyd 1973). The structure is not
        space-filling (dimension &lt; 2) but far more intricate than a smooth
        curve (dimension &gt; 1): it is the canonical example of a
        two-dimensional fractal that grows by tangency rather than by iteration
        of a single affine map.
      </p>
      <p>
        Compare with the other fractal tutorials in the studio library.{" "}
        <Link
          href="/tutorials/blender-tutorial-python-numpy-mandelbrot-julia-fractal-poi-webxr"
          className={lk}
        >
          Mandelbrot and Julia sets
        </Link>{" "}
        are escape-time fractals — every pixel is classified by how many
        iterations it takes to diverge. Apollonian packing is a{" "}
        <em>tangency fractal</em>: the geometry is exact and algebraic, not
        asymptotic. Every circle in the packing can be named by a finite path
        through the BFS tree.{" "}
        <Link
          href="/tutorials/blender-tutorial-python-numpy-dla-diffusion-limited-aggregation-dendritic-crystal-webxr"
          className={lk}
        >
          DLA (diffusion-limited aggregation)
        </Link>{" "}
        is stochastic — each run looks different. An Apollonian gasket seeded
        from the same four circles is deterministic and unique.
      </p>

      <h2>Descartes' theorem and the complex extension</h2>
      <p>
        Four mutually tangent circles with curvatures k₁, k₂, k₃, k₄ (where
        curvature = 1/radius, negative for an enclosing circle) satisfy:
      </p>
      <pre>{`(k1+k2+k3+k4)² = 2(k1²+k2²+k3²+k4²)`}</pre>
      <p>
        Solving for k₄ given k₁, k₂, k₃:
      </p>
      <pre>{`k4 = k1+k2+k3 ± 2√(k1·k2 + k2·k3 + k3·k1)`}</pre>
      <p>
        The ± yields two solutions — the two circles tangent to the given three.
        For a gap, the smaller circle (larger k, inner solution) is the one that
        fits. The centre follows from the{" "}
        <em>complex Descartes theorem</em> (Gossett 1937, rediscovered by
        Wilker 1969):
      </p>
      <pre>{`kz4 = kz1+kz2+kz3 ± 2√(kz1·kz2 + kz2·kz3 + kz3·kz1)`}</pre>
      <p>
        where <code>kz = k · (cx + i·cy)</code> is the complex curvature. This
        gives both k₄ and the centre z₄ = kz₄ / k₄ in one pass.
      </p>

      <h2>The mirror formula — no square root in the recursion</h2>
      <p>
        In the BFS over quadruples the ±√ formula is never needed after the
        first step. Given a quadruple (c₁, c₂, c₃, c₄), both solutions of
        the Descartes quadratic for c₁ are the two roots of a monic quadratic
        whose sum of roots equals <code>2(k₂+k₃+k₄)</code>. One root is c₁
        itself (already known). Therefore the complement is:
      </p>
      <pre>{`k_new  = 2(k2+k3+k4)  - k1
kz_new = 2(kz2+kz3+kz4) - kz1`}</pre>
      <p>
        This is why the canonical gasket seeded from (−1, 2, 2, 3) has only
        integer curvatures everywhere: subtraction and multiplication by 2
        preserve integers, and the seed is already integer. The result —
        confirmed computationally to millions of circles and proved rigorously
        by Sarnak in 2007 — means every circle in the packing can be labelled
        by its integer curvature k.
      </p>

      <h2>BFS over quadruples and deduplication</h2>
      <p>
        The algorithm maintains a queue of 4-tuples of circles. For each
        quadruple, it generates four new circles, one per{" "}
        <em>interstice</em> (replacing each circle with its mirror). Each new
        circle forms a new quadruple with the three it was tangent to. Without
        deduplication the tree expands to infinity even at finite depth, because
        many quadruples share circles.
      </p>
      <p>
        The deduplication key is{" "}
        <code>(round(k), round(cx, 5), round(cy, 5))</code> — curvature plus
        rounded centre. Because the complex Descartes formula is exact rational
        arithmetic when seeded from integers (centres are rational multiples of
        irrationals, but the rounding at 5 decimal places keeps collisions
        below the circle-radius threshold at the resolution we target), this is
        sufficient for K_MAX = 180. At K_MAX ≫ 1 000 a higher-precision
        arithmetic library (Python{" "}
        <code>decimal</code> or <code>fractions</code>) avoids floating-point
        drift.
      </p>
      <p>
        Compare with the{" "}
        <Link
          href="/tutorials/blender-tutorial-python-numpy-penrose-p3-rhombus-quasicrystal-stage-floor-webxr"
          className={lk}
        >
          Penrose P3 quasicrystal tutorial
        </Link>
        , which also builds a stage floor from a mathematical packing rule
        (rhombus deflation substitution). The two outputs look superficially
        similar — dense centres, sparse edges — but Penrose is quasiperiodic
        while Apollonian is fractal: the Apollonian self-similarity is exact
        under Möbius inversion, while Penrose self-similarity is under affine
        scaling.
      </p>

      <h2>Bas-relief height mapping</h2>
      <p>
        Height is mapped logarithmically:{" "}
        <code>h = EXTRUDE_MIN + (EXTRUDE_MAX − EXTRUDE_MIN) · t</code> where{" "}
        <code>t = (log k − log k_min) / (log k_max − log k_min)</code>. Using
        log rather than linear scale is critical: the curvatures span 1 to 180
        linearly but the majority of circles cluster at high k (many small
        circles per level). A linear height map would make the tall pillars
        invisible alongside a few large flat plateaux. Log compresses the range
        so that the overall bas-relief reads as a coherent hillscape rather than
        flat ground with a few spikes.
      </p>
      <p>
        This is the same principle used in the{" "}
        <Link
          href="/tutorials/blender-tutorial-python-numpy-marching-cubes-gyroid-sdf-isosurface-webxr"
          className={lk}
        >
          gyroid isosurface tutorial
        </Link>{" "}
        for wall-thickness mapping: the useful geometric information lives in
        the log domain.
      </p>

      <h2>Single-BMesh construction</h2>
      <p>
        All circles are written into one BMesh rather than creating one object
        per circle. With 700–1 400 circles, creating separate Blender objects
        would require 700–1 400 <code>bpy.ops.object.add</code> calls — each
        needing a UI context round-trip — and the result would be a scene with
        thousands of objects, slow to select or export. A single BMesh with all
        cylinder geometry is built in a Python loop, converted to one mesh
        object, and exported as one GLB node. The GLB draw call count is 1
        rather than 1 400.
      </p>

      <h2>Outside sources and attribution</h2>
      <ul>
        <li>
          Descartes, R. (1643).{" "}
          <em>Letter to Princess Elisabeth.</em> First statement of the
          four-circle tangency theorem. Mathematical content public domain.{" "}
          <a
            href="https://en.wikipedia.org/wiki/Descartes%27_theorem"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            Descartes&apos; theorem (Wikipedia)
          </a>
          .
        </li>
        <li>
          Soddy, F. (1936). &ldquo;The Kiss Precise.&rdquo;{" "}
          <em>Nature</em> 137: 1021. Public domain. The poem that popularised
          Descartes&apos; theorem and gave the Soddy circles their name.{" "}
          <a
            href="https://doi.org/10.1038/137021a0"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            doi:10.1038/137021a0
          </a>
          . Related: Laxton, T. W., ed. (1936) further generalisations,{" "}
          <a
            href="https://mathworld.wolfram.com/ApollonianGasket.html"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            MathWorld Apollonian Gasket
          </a>
          .
        </li>
      </ul>

      <h2>Troubleshooting</h2>
      <ul>
        <li>
          <strong>Gasket appears as a single large circle only.</strong> The
          BFS queue never expanded. Check that <code>K_MAX &gt; 3</code> (the
          first child circle has k = 6). If <code>K_MAX = 3</code> only the
          seed is emitted.
        </li>
        <li>
          <strong>Floating-point drift: small circles appear off-centre.</strong>{" "}
          Increase <code>ROUND_DP</code> to 7 or use Python{" "}
          <code>fractions.Fraction</code> for seed curvatures and switch to
          <code>decimal.Decimal</code> for the BFS arithmetic.
        </li>
        <li>
          <strong>GLB export fails: &apos;no active object&apos;.</strong> The
          script calls{" "}
          <code>bpy.context.view_layer.objects.active = obj</code> before
          exporting; if the Scripting workspace has a pinned context this may
          be overridden. Add{" "}
          <code>bpy.ops.object.select_all(action=&apos;DESELECT&apos;)</code>{" "}
          followed by <code>obj.select_set(True)</code> before the export call.
        </li>
        <li>
          <strong>Script runs for minutes at K_MAX = 500+.</strong> The BFS
          queue size grows exponentially. At K_MAX = 180 expect ≈ 1 000–2 000
          circles and ≈ 3–10 s. At K_MAX = 500 expect ≈ 10 000 circles and
          several minutes. For deep packings switch to a visited-quadruple
          check on integer curvature tuples (faster key hashing than float
          tuples).
        </li>
      </ul>
    </>
  );
}

const blenderTutorialPythonNumpyApollonianCirclePackingSoddyDescartesStageFloorWebxrEntry: Entry =
  buildInstructable(
    {
      steps: [
        {
          title: "Generate Apollonian packing",
          body: "Call generate_apollonian(SEED, K_MAX=180). Starts from 4-tuple [(-1,0),(2,1),(2,-1),(3,2i)], BFS over quadruples using mirror formula k_new = 2(k2+k3+k4)−k1. Deduplicates on (round(k), round(cx,5), round(cy,5)). Returns list of (k, cx, cy, r) for all positive-curvature circles.",
        },
        {
          title: "Map circles to bas-relief heights",
          body: "Compute log-scale height t = (log k − log k_min)/(log k_max − log k_min) for each circle. Height h = EXTRUDE_MIN + (EXTRUDE_MAX−EXTRUDE_MIN)·t. Smallest circles (largest k) → tallest pillars.",
        },
        {
          title: "Build single BMesh",
          body: "One bmesh.new() for all circles. Per circle: add SEG bottom verts at (cx±r·cosθ, cy±r·sinθ, 0), SEG top verts at same XY but z=h, one top-centre vert. Add SEG side quads and SEG top-fan triangles. Call bmesh.ops.recalc_face_normals at the end.",
        },
        {
          title: "Convert and flat-shade",
          body: "bm.to_mesh(me), create Object, link to scene collection. Set poly.use_smooth=False for every polygon — flat shading gives faceted look consistent with studio aesthetic.",
        },
        {
          title: "Assign emission material",
          body: "Emission node with Strength=3.0. ColourRamp on ObjectInfo.Random: violet (0.60,0.15,1.0) → cyan (0.08,0.90,0.95). No UV needed — random object colour per instance varies by position.",
        },
        {
          title: "Export Draco-6 GLB",
          body: "export_apply=True, export_yup=True, Draco level 6, WEBP textures. GLB writes to hf_apollonian_floor.glb alongside the blend file.",
        },
        {
          title: "Run viewport animation",
          body: "Run record.py: top-down orbit F1-60, tilt from 70°→25° F61-150, EEVEE Next 16 samples, bloom threshold 0.6. Output → videos/scripting/.../viewport.mp4.",
        },
      ],
      troubleshooting: [
        {
          symptom: "Only one large circle visible",
          cause: "K_MAX ≤ 3 — BFS never finds k_new < K_MAX.",
          fix: "Increase K_MAX to at least 20.",
        },
        {
          symptom: "Small circles off-centre (floating-point drift)",
          cause: "ROUND_DP too low for the depth reached.",
          fix: "Set ROUND_DP=7 or switch to Python fractions/decimal arithmetic.",
        },
        {
          symptom: "Script slow at K_MAX > 300",
          cause: "BFS queue grows exponentially with max curvature.",
          fix: "Reduce K_MAX or switch visited-quadruple key to integer tuple (faster hashing).",
        },
        {
          symptom: "GLB export: no active object",
          cause: "Scripting workspace context override.",
          fix: "Add bpy.ops.object.select_all(action='DESELECT'); obj.select_set(True) before export call.",
        },
      ],
      voiceMode: "aura",
    },
    {
      slug: SLUG,
      title: TITLE,
      date: "2026-08-01",
      kind: "tutorial",
      excerpt: LEDE,
      tags: [
        "blender",
        "python",
        "fractal",
        "apollonian",
        "circle-packing",
        "descartes",
        "soddy",
        "procedural",
        "stage-floor",
        "webxr",
        "bmesh",
        "bas-relief",
        "tangency",
        "geometry",
      ],
      Body,
    },
  );

export const entry =
  blenderTutorialPythonNumpyApollonianCirclePackingSoddyDescartesStageFloorWebxrEntry;
