import Link from "next/link";

import { buildInstructable } from "lib/tutorials/build";
import type { Entry } from "lib/writing";

const lk = "underline underline-offset-4 hover:text-pink-200";

const SLUG =
  "blender-tutorial-python-numpy-involute-gear-profile-module-system-trochoidal-fillet-mating-pair-webxr";

const TITLE =
  "Python numpy — Involute Gear: Base-Circle Involute, Module System, Trochoidal Root Fillet & Mating Pair for WebXR (Blender 5.1)";

const LEDE =
  "In 1867 Charles Holtzapffel established the involute tooth form as the industrial standard, building on Leonhard Euler's 1754 observation that a curve unrolled from a circle produces conjugate motion.  The involute is the unique tooth shape that keeps the angular-velocity ratio constant regardless of small centre-distance error — a property cycloidal gears lack entirely.  This blueprint constructs a mathematically correct 20-tooth / 40-tooth spur-gear pair in Blender 5.1 using Python and numpy: the tooth flanks come from the analytic involute of the base circle, the root fillets are trochoidal envelopes generated by the rolling rack cutter tip, and the whole assembly exports as a Draco-compressed GLB with per-vertex cyan-to-magenta emission colour tracing the pressure path from root to tip.";

const data = {
  title: TITLE,
  lede: LEDE,
  date: "2026-08-09",
  externalSources: [
    {
      label:
        "Blender Foundation. Blender Python API Reference 5.1. CC-BY-SA-4.0. Blender Foundation, 2024.",
      url: "https://docs.blender.org/api/5.1/",
      licence: "CC-BY-SA-4.0",
      author: "Blender Foundation",
    },
    {
      label:
        "NumPy community. NumPy User Guide. BSD-3-Clause. NumPy contributors, 2024.",
      url: "https://numpy.org/doc/stable/user/",
      licence: "BSD-3-Clause",
      author: "NumPy contributors",
    },
    {
      label:
        "Khronos Group. glTF-Blender-IO. Apache-2.0. Khronos Group, 2024.",
      url: "https://github.com/KhronosGroup/glTF-Blender-IO",
      licence: "Apache-2.0",
      author: "Khronos Group",
    },
  ],
};

function Body() {
  return (
    <>
      <p>
        An <em>involute</em> is the curve traced by the tip of a taut string as
        it unwinds from a circle.  When two gears are cut with the same base
        circle relationship, their involute flanks always touch on the{" "}
        <strong>line of action</strong> — the common tangent to both base circles
        — and the contact point moves smoothly along that line.  This is
        conjugate action: the driven shaft turns at exactly the ratio you
        specified, without velocity ripple.
      </p>

      <h2>The module system</h2>
      <p>
        Every derived gear dimension follows from two numbers: the{" "}
        <strong>module</strong> <em>m</em> (tooth size in millimetres) and the
        <strong> tooth count</strong> <em>N</em>.  The pitch radius is simply
        r_p = m·N/2.  Two gears mesh when they share the same module and
        pressure angle — the rest is arithmetic.
      </p>
      <pre className="overflow-x-auto rounded bg-neutral-800 p-3 text-sm text-cyan-200">
        {`r_p  = m · N / 2          # pitch radius
r_b  = r_p · cos(φ)      # base radius (involute origin)
r_a  = r_p + m            # addendum (tip) radius
r_f  = r_p − 1.25·m      # dedendum (root) radius`}
      </pre>
      <p>
        With module 1 and N = 20 / 40, the centre distance is exactly
        10 + 20 = 30 mm.
      </p>

      <h2>Parametric involute</h2>
      <p>
        The unwinding parameter <em>t</em> is also the tangent length from the
        base circle to the contact point.  In Cartesian coordinates:
      </p>
      <pre className="overflow-x-auto rounded bg-neutral-800 p-3 text-sm text-cyan-200">
        {`x(t) = r_b · (cos t + t·sin t)
y(t) = r_b · (sin t − t·cos t)
r(t) = r_b · √(1 + t²)          # radial distance at parameter t`}
      </pre>
      <p>
        The flank runs from t = 0 (base circle) to{" "}
        <code>t_tip = √((r_a/r_b)² − 1)</code> (tip circle).  In Python:
      </p>
      <pre className="overflow-x-auto rounded bg-neutral-800 p-3 text-sm text-cyan-200">
        {`def involute_pt(r_b, t):
    return np.array([
        r_b * (np.cos(t) + t * np.sin(t)),
        r_b * (np.sin(t) - t * np.cos(t)),
    ])`}
      </pre>
      <p>
        Twenty-eight sample points along this curve give a smooth flank with
        no faceting visible at WebXR viewing distance.
      </p>

      <h2>Aligning the flank with the tooth centreline</h2>
      <p>
        The standard involute starts on the +X axis.  We need the right flank
        to lie at the correct angular distance from the tooth centreline (+Y).
        The involute function <code>inv(φ) = tan φ − φ</code> encodes the
        involute angle at the pressure angle:
      </p>
      <pre className="overflow-x-auto rounded bg-neutral-800 p-3 text-sm text-cyan-200">
        {`alpha_p = π / (2·N)           # half tooth thickness at pitch circle
rot     = π/2 − (alpha_p + inv(φ))  # rotation into tooth frame`}
      </pre>
      <p>
        Applying this rotation to every sample point places the involute
        symmetrically about +Y, ready for replication around Z at the tooth
        angular pitch 2π/N.
      </p>

      <h2>Trochoidal root fillet</h2>
      <p>
        The gap between teeth is machined by a rack cutter whose tip carries a
        fillet circle of radius ρ = 0.38m (ISO standard).  As the rack rolls
        without slipping on the pitch circle, the centre of that circle traces
        a <strong>trochoid</strong> in gear coordinates:
      </p>
      <pre className="overflow-x-auto rounded bg-neutral-800 p-3 text-sm text-cyan-200">
        {`# θ = rolling angle, d = depth of fillet centre below pitch line
x_c(θ) = (r_p − d)·sin θ + r_p·θ·cos θ
y_c(θ) = (r_p − d)·cos θ − r_p·θ·sin θ`}
      </pre>
      <p>
        The fillet curve is the trochoid offset outward by ρ.  Unlike a simple
        circular arc, the true trochoidal fillet distributes bending stress over
        a wider root cross-section and prevents the re-entrant notch that
        concentrates fatigue cracks.
      </p>

      <h2>Undercut criterion</h2>
      <p>
        If the involute is extended below the base circle, it tries to fold back
        — creating interference with the mating gear&rsquo;s tip.  The minimum tooth
        count to avoid undercut is:
      </p>
      <pre className="overflow-x-auto rounded bg-neutral-800 p-3 text-sm text-cyan-200">
        {`N_min = 2 / sin²(φ) ≈ 17.1   for φ = 20°`}
      </pre>
      <p>
        Both gears here (N = 20 and N = 40) are safely above this limit.  The
        blueprint clamps the root circle to 80% of the base radius for smaller N
        so the profile remains self-consistent even if you experiment with N = 12.
      </p>

      <h2>Full tooth assembly</h2>
      <p>
        The complete tooth boundary is assembled in order:
        right fillet → right involute → tip arc → left involute (mirrored) →
        left fillet (mirrored).  This polygon is then replicated N times at
        angular pitch 2π/N around Z, extruded by the face width, and triangulated
        by bmesh for export.
      </p>

      <h2>Vertex colour: pressure path</h2>
      <p>
        Each vertex is coloured by its radial distance from root to tip,
        interpolating cyan (r_f) → magenta (r_a).  The colour gradient follows
        the contact path during meshing — at any instant the active contact point
        travels from the root of one tooth to the tip of the other, tracing the
        hue shift from cyan to magenta along the line of action.
      </p>

      <h2>Mating pair alignment</h2>
      <p>
        The driven gear (N = 40) is placed at the correct centre distance and
        rotated by half its tooth angular pitch π/N₂ so the teeth interleave
        at frame 1.  Conjugate angular velocities satisfy:
      </p>
      <pre className="overflow-x-auto rounded bg-neutral-800 p-3 text-sm text-cyan-200">
        {`ω_driven = −ω_drive · (N_drive / N_driven)
         = −ω_drive · (20 / 40)
         = −ω_drive / 2`}
      </pre>
      <p>
        The record.py script keyframes both rotations with linear interpolation
        so the animation plays at 0.5 rotations per second without Bézier drift.
      </p>

      <h2>Trade-offs and failure modes</h2>
      <ul className="list-disc list-inside space-y-1">
        <li>
          <strong>n-gon front/back faces</strong> — bmesh creates large n-gon
          faces for the gear discs.  The GLB exporter triangulates these on
          export; for very high N (≥ 64) the triangulation diagonals can
          produce shading artefacts.  Fix by adding explicit triangle fans from
          the gear centre.
        </li>
        <li>
          <strong>Module mismatch</strong> — gears only mesh correctly when
          module and pressure angle are identical.  Changing MODULE on one gear
          without updating the other shifts the pitch circles and produces
          clashing or gapping.
        </li>
        <li>
          <strong>Shape-key vertex-count requirement</strong> — Blender shape
          keys require identical vertex counts.  To morph between different N
          values you must pad the smaller profile to the vertex count of the
          largest N, zeroing unused points at the gap centres.
        </li>
        <li>
          <strong>Helical extension</strong> — spur gears produce impulse loads.
          For a helical gear variant, rotate each cross-section by a helix angle
          as you extrude along Z; the involute geometry on each slice is unchanged.
        </li>
      </ul>

      <h2>Cross-references</h2>
      <p>Related Holoflow studio work:</p>
      <ul className="list-disc list-inside space-y-1">
        <li>
          <Link href="/tutorials/blender-tutorial-gn-scene-time-rotation-mechanical-clockwork" className={lk}>
            GN Scene Time — Mechanical Clockwork
          </Link>{" "}
          — procedural gear animation using Geometry Nodes Scene Time and
          Rotation sockets; compare the simplified 4-vertex tooth approximation
          used there with the full involute profile here.
        </li>
        <li>
          <Link href="/tutorials/blender-tutorial-python-numpy-hypotrochoid-epitrochoid-spirograph-roulette-poi-ring-webxr" className={lk}>
            Hypotrochoid & Epitrochoid
          </Link>{" "}
          — the roulette curves that a rack cutter generates on the gear body
          are epitrochoids; same rolling-circle mathematics, different context.
        </li>
        <li>
          <Link href="/tutorials/blender-tutorial-python-bpy-bmesh-dodecahedron" className={lk}>
            Python bmesh Dodecahedron
          </Link>{" "}
          — the same direct bmesh construction pattern (
          <code>bm.verts.new</code> / <code>bm.faces.new</code> /
          <code>bm.to_mesh</code>) used for the gear disc faces.
        </li>
      </ul>
    </>
  );
}

export const entry: Entry = buildInstructable(
  {
    slug: SLUG,
    title: TITLE,
    lede: LEDE,
    date: data.date,
    tags: ["blender", "python", "numpy", "geometry", "mechanical", "webxr"],
    externalSources: data.externalSources,
  },
  Body,
);
