import Link from "next/link";

import { buildInstructable } from "lib/tutorials/build";
import type { Entry } from "lib/writing";

const lk = "underline underline-offset-4 hover:text-pink-200";

const SLUG =
  "blender-tutorial-python-numpy-icosahedral-quasicrystal-cut-project-z6-shechtman-poi-head-webxr";

const TITLE =
  "Python numpy — Icosahedral Quasicrystal: 6D Cut-and-Project, Z⁶ Lattice, Galois Conjugate Star Vectors & Aperiodic Poi Head for WebXR (Blender 5.1)";

const LEDE =
  "In 1984 Dan Shechtman observed 5-fold icosahedral diffraction symmetry in Al-Mn alloys — geometrically forbidden by the 230 classical space groups.  The mathematical explanation is that a quasicrystal is a 3-D 'shadow' of a 6-D cubic lattice: each atom is the physical-space projection x∥ = P∥ n of a lattice point n ∈ Z⁶ whose perpendicular-space projection x⊥ = P⊥ n falls inside an acceptance window.  This blueprint constructs the full cut-and-project machinery in pure numpy — deriving the projection matrices from the Galois conjugate of the golden ratio, enumerating 7⁶ = 117,649 candidates, applying the spherical acceptance window in E⊥, finding the two bond lengths in ratio τ:1, extruding edge tubes and vertex beads into a single bmesh, and exporting a 12 cm poi head as a Draco-6 GLB with vertex-colour emission for WebXR.";

const data = {
  title: TITLE,
  lede: LEDE,
  date: "2026-08-09",
  externalSources: [
    {
      label:
        "Shechtman, D., Blech, I., Gratias, D. & Cahn, J. W. (1984). Metallic Phase with Long-Range Orientational Order and No Translational Symmetry. Physical Review Letters, 53(20), 1951–1953. Public Domain (mathematical content / 1984).",
      url: "https://doi.org/10.1103/PhysRevLett.53.1951",
      licence: "Public Domain (mathematical content / 1984)",
      author: "Shechtman, Blech, Gratias & Cahn",
    },
    {
      label:
        "Duneau, M. & Katz, A. (1985). Quasiperiodic Patterns. Physical Review Letters, 54(25), 2688–2691. Public Domain (mathematical content / 1985). Related: Kalugin-Kitaev-Levitov (1985); de Bruijn (1981) algebraic theory of Penrose tilings.",
      url: "https://doi.org/10.1103/PhysRevLett.54.2688",
      licence: "Public Domain (mathematical content / 1985)",
      author: "Duneau & Katz",
    },
    {
      label:
        "NumPy contributors. NumPy Reference Documentation. BSD-3-Clause. Related: github.com/numpy/numpy.",
      url: "https://numpy.org/doc/stable/",
      licence: "BSD-3-Clause",
      author: "NumPy community",
    },
  ],
};

function Body() {
  return (
    <>
      <p>
        Classical crystallography forbids 5-fold symmetry: no lattice can tile
        space with a 5-fold rotation axis because 2π/5 does not divide 2π an
        integer number of times.  Shechtman&apos;s electron diffraction spots
        nonetheless formed a perfect icosahedral pattern — ten-fold rings at
        angles arccos(1/√5) ≈ 63.4° from the 5-fold axis.  The resolution is
        the <em>quasiperiodic</em> state: long-range order without
        translational periodicity, generated by projecting a higher-dimensional
        periodic lattice.
      </p>

      <h2>The 6D → 3D projection</h2>
      <p>
        Write ℝ⁶ = E∥ ⊕ E⊥ where E∥ is &ldquo;physical space&rdquo; and E⊥
        is the &ldquo;internal&rdquo; or perpendicular complement.  The 6
        icosahedral star vectors in E∥ are normalised icosahedral vertices:
      </p>
      <pre className="overflow-x-auto rounded bg-zinc-900 p-3 text-sm">
        {`τ = (1 + √5) / 2 ≈ 1.618   (golden ratio)
norm = √(1 + τ²) = √(τ + 2) ≈ 1.902

E∥ star vectors (rows of P∥, 6×3):
  [0,  1,  τ] / norm
  [0, -1,  τ] / norm
  [τ,  0,  1] / norm
  [-τ, 0,  1] / norm
  [1,  τ,  0] / norm
  [-1, τ,  0] / norm`}
      </pre>
      <p>
        These are 6 of the 12 icosahedral vertices (one from each antipodal
        pair).  The perpendicular-space complement is obtained by the Galois
        conjugation τ ↦ −1/τ:
      </p>
      <pre className="overflow-x-auto rounded bg-zinc-900 p-3 text-sm">
        {`τ̄ = −1/τ = (1 − √5) / 2 ≈ −0.618   (Galois conjugate)

E⊥ star vectors (rows of P⊥, 6×3):
  [0,  1,  τ̄] / norm⊥  …  same layout, τ replaced by τ̄`}
      </pre>

      <h2>Why the Galois conjugate?</h2>
      <p>
        The inflation matrix of the icosahedral tiling has eigenvalues τ
        (physical, expanding) and −1/τ (perpendicular, contracting).  Replacing
        τ → −1/τ maps E∥ isometrically onto E⊥ — the two subspaces are Galois
        images of each other under ℚ(√5) → ℚ(√5).  This guarantees that P∥
        and P⊥ together form a partition of unity: P∥ᵀP∥ + P⊥ᵀP⊥ = I₆.
        Without this, the two projections would not cover Z⁶ ⊗ ℝ completely.
      </p>

      <h2>Acceptance window and bond lengths</h2>
      <p>
        For each n ∈ Z⁶ within [−3,3]⁶ (7⁶ = 117,649 points), compute
        x⊥ = P⊥ n.  Accept if |x⊥| &lt; R_window.  Typical yield: 400–950
        vertices.  In the accepted set, exactly two edge lengths appear:
      </p>
      <pre className="overflow-x-auto rounded bg-zinc-900 p-3 text-sm">
        {`l_short = min non-zero pairwise distance in E∥
l_long  = τ · l_short

Bond criterion: |P∥ nₐ − P∥ n_b| ≤ l_short × (1 + BOND_MAX_FRAC)
BOND_MAX_FRAC = 0.72 keeps both bond types; > 1.0 would add next-neighbour arcs`}
      </pre>
      <p>
        This two-length rule is the 3-D analogue of the Penrose tiling&apos;s
        thin and fat rhombus edge lengths.
      </p>

      <h2>Blueprint walkthrough</h2>
      <pre className="overflow-x-auto rounded bg-zinc-900 p-3 text-sm">
        {`# 1. Build projection matrices
P_PHYS = _star_vectors(PHI)          # (6,3) physical
P_PERP = _star_vectors(-1/PHI)       # (6,3) perpendicular

# 2. Enumerate Z⁶ lattice
lattice = np.meshgrid(*([ax]*6), indexing='ij')  # 7^6 × 6
lattice = np.stack([g.ravel() for g in lattice], axis=-1)

# 3. Cut: accept if |P⊥ n| < R_window
perp = lattice @ P_PERP              # (N, 3)
mask = np.linalg.norm(perp, axis=1) < R_window
pts  = (lattice @ P_PHYS)[mask]      # (M, 3) in E∥

# 4. Find bonds (brute force, M ≈ 500–900)
d = pts[:,None,:] - pts[None,:,:]    # (M,M,3)
edges = np.where((d<bond_max) & (d>0))   # upper-triangle filtered`}
      </pre>

      <h2>Failure modes & troubleshooting</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li>
          <strong>No vertices accepted.</strong> R_window too small — the Z⁶
          perpendicular projections all exceed it.  Start with R_window = 1.95;
          the maximum perpendicular radius for N_RANGE=3 is ≈2.8.
        </li>
        <li>
          <strong>Only one bond length visible.</strong> BOND_MAX_FRAC is below
          the short-to-long ratio (0.618).  Set BOND_MAX_FRAC = 0.72 to admit
          both.
        </li>
        <li>
          <strong>MemoryError on large N_RANGE.</strong> 7⁶ = 117,649 points
          for N_RANGE=3 is fine.  8⁶ = 262,144 and 9⁶ = 531,441 may OOM when
          the brute-force O(M²) pairwise distance matrix is computed.  Switch
          to a KD-tree (scipy.spatial.cKDTree) for N_RANGE ≥ 4.
        </li>
        <li>
          <strong>bpy.ops.export_scene.gltf context error in headless mode.</strong>{" "}
          This operator requires a scene context.  Workaround: call with
          bpy.context.temp_override(scene=bpy.context.scene) or use
          bpy.ops.export_scene.gltf via the C-level direct call in Blender 5.x.
        </li>
      </ul>

      <h2>Cross-references</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-penrose-p3-rhombus-quasicrystal-stage-floor-webxr"
            className={lk}
          >
            Penrose P3 Quasicrystal: Rhombus Tiling & Multigrid Dual
          </Link>{" "}
          — the 2-D parent.  The same two-length ratio τ:1 appears in P3
          (thin/fat rhombus), and the acceptance strip in this 2-D case is a
          1-D interval (the 1-D window).  The 3-D quasicrystal inherits the
          same τ-chain arithmetic.
        </li>
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-scipy-wigner-seitz-bcc-fcc-brillouin-zone-3d-voronoi-poi-head-webxr"
            className={lk}
          >
            Wigner-Seitz Cell: BCC/FCC Brillouin Zone & 3-D Voronoi
          </Link>{" "}
          — in a periodic lattice the acceptance window is trivially the entire
          unit cell.  Comparing the rhombicosidodecahedral quasicrystal window
          to a Wigner-Seitz cell shows why aperiodicity requires a non-convex
          (or at least non-tiling) internal window in E⊥.
        </li>
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-24-cell-icositetrachoron-d4-root-lattice-stereographic-poi-webxr"
            className={lk}
          >
            24-Cell {"{3,4,3}"}: D₄ Root Lattice & Stereographic Projection
          </Link>{" "}
          — another higher-dimensional lattice projected to 3-D.  The 24-cell
          is a 4-polytope; the quasicrystal uses a 6-polytope (hypercubic)
          and a non-orthographic projection (P∥ is not a coordinate-slice).
        </li>
        <li>
          <Link
            href="/tutorials/blender-tutorial-python-numpy-hopf-fibration-s3-s2-fiber-bundle-linked-circles-poi-webxr"
            className={lk}
          >
            Hopf Fibration: S³ → S² Principal Bundle
          </Link>{" "}
          — icosahedral symmetry appears in the Hopf fibration context because
          the binary icosahedral group 2I ⊂ SU(2) ≅ S³ acts on the fibres;
          the 120 elements of 2I are the vertices of the 600-cell in S³.
        </li>
      </ul>

      <h2>Outside sources</h2>
      <ol className="list-decimal pl-5 space-y-2">
        <li>
          <strong>
            <a
              href="https://doi.org/10.1103/PhysRevLett.53.1951"
              className={lk}
              target="_blank"
              rel="noopener noreferrer"
            >
              Shechtman, D., Blech, I., Gratias, D. &amp; Cahn, J. W. (1984).
              Metallic Phase with Long-Range Orientational Order and No
              Translational Symmetry. PRL 53(20):1951–1953.
            </a>
          </strong>{" "}
          — the Nobel Prize (2011) paper.  Fig. 2 shows the 10-fold diffraction
          pattern whose icosahedral symmetry the cut-and-project construction
          explains.  Related: Levine &amp; Steinhardt (1984) &ldquo;Quasicrystals:
          A New Class of Ordered Structure&rdquo; PRL 53(26) — coined the term
          &ldquo;quasicrystal&rdquo;; Elser (1985) indexing formula for
          icosahedral diffraction spots.
        </li>
        <li>
          <strong>
            <a
              href="https://doi.org/10.1103/PhysRevLett.54.2688"
              className={lk}
              target="_blank"
              rel="noopener noreferrer"
            >
              Duneau, M. &amp; Katz, A. (1985). Quasiperiodic Patterns.
              PRL 54(25):2688–2691.
            </a>
          </strong>{" "}
          — the paper that established the cut-and-project formalism used here.
          Eqs. (3)–(5) define the projection matrices P∥ and P⊥ in exactly the
          form implemented in blueprint.py.  Related: Kalugin, Kitaev &amp;
          Levitov (1985) independent derivation for Al₀.₈₆Mn₀.₁₄; de Bruijn
          (1981) algebraic theory of Penrose tilings (the 2-D forerunner of this
          construction).
        </li>
        <li>
          <strong>
            <a
              href="https://numpy.org/doc/stable/"
              className={lk}
              target="_blank"
              rel="noopener noreferrer"
            >
              NumPy contributors. NumPy Reference Documentation. BSD-3-Clause.
            </a>
          </strong>{" "}
          — meshgrid, broadcast matrix multiplication, and linalg.norm power the
          entire 7⁶-point enumeration and acceptance-window test in under 2 s.
          Related:{" "}
          <a
            href="https://github.com/numpy/numpy"
            className={lk}
            target="_blank"
            rel="noopener noreferrer"
          >
            github.com/numpy/numpy
          </a>
          .
        </li>
      </ol>
    </>
  );
}

export const entry: Entry = buildInstructable({
  ...data,
  slug: SLUG,
  body: <Body />,
});
