import Link from "next/link";

import { buildInstructable } from "lib/tutorials/build";
import type { Entry } from "lib/writing";

const lk = "underline underline-offset-4 hover:text-pink-200";

function Body() {
  return (
    <>
      <p>
        A <em>roulette curve</em> is the path traced by a point fixed to a
        circle rolling without slipping against another circle. Roll inside the
        fixed circle and you have a <strong>hypotrochoid</strong>; roll outside
        and you have an <strong>epitrochoid</strong>. Both families are defined
        by three numbers: fixed-circle radius R, rolling-circle radius r, and
        pen-arm length d. Varying those three numbers sweeps through a vast
        family of named curves — astroid, deltoid, cardioid, nephroid — all
        generated by exactly the same two lines of trigonometry.
      </p>
      <p>
        This blueprint samples six of those curves, wraps each in a{" "}
        <strong>Bishop-frame tube mesh</strong>, and stores them as shape keys
        on a single Blender object. The result is a studio-ready GLB poi ring
        that morphs between geometrically distinct forms without any re-export.
        Compare the Fourier-epicycle approach in the{" "}
        <Link
          href="/tutorials/blender-tutorial-python-numpy-fft-epicycles-fourier-phasor-chain-poi-webxr"
          className={lk}
        >
          FFT Phasor Chain tutorial
        </Link>
        , which decomposes an arbitrary path into rotating circles in the
        frequency domain; roulette curves are the mechanical / time-domain
        origin of the same idea.
      </p>

      <h2>The closed-curve condition</h2>
      <p>
        The curve closes after exactly <em>q</em> revolutions of the rolling
        circle, where q&nbsp;=&nbsp;r&nbsp;/&nbsp;gcd(R,&thinsp;r). When R/r
        is irrational the curve never closes and instead densely fills an
        annulus. For a tube mesh we need closure, so every variant here uses
        rational R:r pairs. For example:
      </p>
      <pre>{`R=5, r=3  →  gcd=1, q=3, period=6π   (5-petalled spirograph)
R=7, r=2  →  gcd=1, q=2, period=4π   (7-lobed rose)
R=4, r=1  →  gcd=1, q=1, period=2π   (astroid, 4 cusps)`}</pre>
      <p>
        The number of apparent lobes/petals in a hypotrochoid is p&nbsp;=&nbsp;R/r
        (when d&nbsp;=&nbsp;r exactly); when d&nbsp;&gt;&nbsp;r the curve develops
        outer loops rather than cusps, which is the &quot;spirograph&quot; regime
        most people recognise.
      </p>

      <h2>Bishop frame through cusps</h2>
      <p>
        Every cusp or inflection point of a roulette curve is a location where
        the rolling-circle velocity instantaneously reverses direction relative
        to the pen arm. At those points the Frenet-Serret principal normal
        flips discontinuously, making the classical Frenet frame undefined and
        the tube mesh twist uncontrollably. The{" "}
        <strong>Bishop parallel-transport frame</strong> propagates the cross-section
        orientation using only tangent information — it is never undefined, even
        at cusps — and requires only a single end-correction step to ensure the
        tube closes without a seam gap.
      </p>
      <p>
        For a deeper treatment of the same frame technique applied to torus
        knots, see the{" "}
        <Link
          href="/tutorials/blender-tutorial-python-mathutils-torus-knot-pq-winding-parallel-transport-tube-webxr"
          className={lk}
        >
          Torus Knot p-q Winding Tube blueprint
        </Link>
        .
      </p>

      <h2>Shape key topology</h2>
      <p>
        All six variants are sampled at the same N_CURVE = 1024 points, so
        every variant has an identical vertex count and the shape keys interpolate
        linearly in Blender without any topology mismatch. The trade-off: N_CURVE
        must be large enough to resolve the finest variant (Rose_7_2 with 7 inner
        loops) without aliasing, which is why 1024 is chosen rather than the
        256 that would suffice for the astroid alone.
      </p>
      <p>
        This is the same multi-morphotype strategy used in the{" "}
        <Link
          href="/tutorials/blender-tutorial-gn-simulation-zone-spring-pendulum-poi-lissajous-light-painting"
          className={lk}
        >
          Spring Pendulum Lissajous GN blueprint
        </Link>{" "}
        (coupled-oscillator Lissajous figures as shape keys) and in the{" "}
        <Link
          href="/tutorials/blender-tutorial-python-numpy-delaunay-cmc-surfaces-unduloid-nodoid-roulette-revolution-poi-webxr"
          className={lk}
        >
          Delaunay CMC roulette-of-conic tutorial
        </Link>
        , which uses the roulette of an ellipse rolling along a straight line
        to generate unduloid and nodoid surfaces of revolution.
      </p>

      <h2>Vertex colour encoding</h2>
      <p>
        Each face is coloured by its spine index as a fraction t&nbsp;∈&nbsp;[0,1),
        mapped to a full HSV rainbow cycle. In the Workbench renderer this makes
        the curve period visually legible — you can count the number of lobe
        repetitions by tracing where the colour gradient repeats. The same
        colour attribute is exported to the GLB and is available as{" "}
        <code>COLOR_0</code> in Three.js for shader access.
      </p>

      <h2>Failure modes</h2>
      <ul>
        <li>
          <strong>Seam crack at the tube join.</strong> This means the
          end-correction twist is wrong, usually because N_CURVE is not a
          multiple of the curve period in samples. Verify that{" "}
          <code>period&nbsp;/&nbsp;(2π)&nbsp;×&nbsp;N_CURVE</code> is an
          integer (it always is for rational R:r with the formula in
          blueprint.py).
        </li>
        <li>
          <strong>BMesh degenerate-face error at cusps.</strong> When d&nbsp;=&nbsp;r
          the curve passes through genuine cusps where consecutive sample points
          are almost co-located. The blueprint catches{" "}
          <code>ValueError</code> on <code>bm.faces.new()</code> and skips those
          faces; the tube will have a tiny hole at each cusp. For the astroid and
          deltoid this is intentional and invisible in WebXR.
        </li>
        <li>
          <strong>Shape key vertex mismatch.</strong> If you change N_CURVE
          between runs without deleting the existing object first, Blender will
          refuse to add shape keys. Always run <code>clear_scene()</code> or
          manually delete the old object.
        </li>
      </ul>
    </>
  );
}

const data = {
  title:
    "Python numpy — Hypotrochoid & Epitrochoid: Rolling-Circle Roulette Geometry, Closed-Curve Condition GCD(R,r) & Bishop-Frame Poi Ring for WebXR",
  lede:
    "Sample six rolling-circle roulette curves (spirograph 5-3, rose 7-2, astroid, deltoid, cardioid, nephroid), build a Bishop-frame tube mesh for each, store them as shape keys on a single GLB poi ring, and encode the curve parameter as a rainbow vertex-colour attribute.",
  date: "2026-08-08",
  steps: [
    {
      title: "Set parameters",
      body: "Open blueprint.py. SCALE_M = 0.15 sets the overall ring diameter to 30 cm. TUBE_R = 0.012 gives a 12 mm tube cross-section — increase to 0.018 for a chunkier ring. N_CURVE = 1024 is the spine resolution; reduce to 512 if the script is slow on older hardware.",
    },
    {
      title: "Run the script",
      body: "In Blender 5.1 Scripting workspace, open blueprint.py and press ▶ Run Script. The terminal will print the variant list and the final vertex/face count. Expect 73,728 vertices (1024 × 12 × 6 shape-key targets are not additive — only the active shape uses memory).",
    },
    {
      title: "Preview the shape keys",
      body: "Switch to 3D Viewport → Material Preview (Z → Material Preview). Open the N-Panel → Object Properties → Shape Keys. Scrub each key from 0 to 1 to see the transition: Spirograph_5_3 has 5 outer loops; Astroid has 4 sharp cusps; Cardioid has the distinctive heart indent.",
    },
    {
      title: "Inspect vertex colours",
      body: "In Viewport Shading (top-right sphere icon), enable Colour → Vertex. The rainbow cycle should repeat exactly once per lobe period. If the colours smear across the entire ring without repeating, the spine-index → face-index mapping in the colour loop needs adjusting — see the comment in blueprint.py.",
    },
    {
      title: "Export GLB",
      body: "Select hf_spirograph_poi. File → Export → glTF 2.0. Tick Selected Objects. Set Draco compression level 6, Image format WebP. Under Data → Mesh, tick Include Shape Keys. Under Transform, tick +Y Up. The GLB will contain all six morph targets and the COLOR_0 vertex attribute.",
    },
    {
      title: "Render viewport animation",
      body: "Run record.py in the same session (after blueprint.py). It adds a camera, animates the shape keys in sequence, and renders viewport.mp4 at 1920×1080 30 fps using Workbench FLAT vertex-colour mode. The 240-frame render takes 30–90 s on CPU.",
    },
    {
      title: "Screen recording",
      body: "Follow SCREEN-RECORDING-NOTES.md. The key interaction to capture is scrubbing each shape key while in Material Preview mode — the deformation is instantaneous and communicates the topology change more clearly than the automated animation.",
    },
  ],
  externalLinks: [
    {
      label:
        "matplotlib Gallery — Animated Spirograph — BSD-3-Clause — Matplotlib Contributors",
      href: "https://matplotlib.org/stable/gallery/animation/animated_spiral.html",
    },
    {
      label:
        "Wikipedia — Hypotrochoid — CC BY-SA 4.0 — Wikipedia Contributors",
      href: "https://en.wikipedia.org/wiki/Hypotrochoid",
    },
    {
      label:
        "NumPy Reference — Mathematical functions — BSD-3-Clause — NumPy Contributors",
      href: "https://numpy.org/doc/stable/reference/routines.math.html",
    },
  ],
  relatedTutorials: [
    {
      label:
        "Python numpy — FFT Epicycles: Fourier-Series Phasor Chain, DFT Coefficient Ordering & Depsgraph Trail",
      href: "/tutorials/blender-tutorial-python-numpy-fft-epicycles-fourier-phasor-chain-poi-webxr",
    },
    {
      label:
        "Python mathutils — Torus Knot T(p,q): Parallel-Transport Tube & Poi Ring for WebXR",
      href: "/tutorials/blender-tutorial-python-mathutils-torus-knot-pq-winding-parallel-transport-tube-webxr",
    },
    {
      label:
        "GN Simulation Zone — Spring Pendulum Poi: Lissajous Light-Painting",
      href: "/tutorials/blender-tutorial-gn-simulation-zone-spring-pendulum-poi-lissajous-light-painting",
    },
    {
      label:
        "Python numpy — Delaunay CMC Surfaces: Unduloid, Nodoid & Roulette of Conic for Poi Head WebXR",
      href: "/tutorials/blender-tutorial-python-numpy-delaunay-cmc-surfaces-unduloid-nodoid-roulette-revolution-poi-webxr",
    },
  ],
};

export const entry: Entry = buildInstructable(
  {
    slug: "blender-tutorial-python-numpy-hypotrochoid-epitrochoid-spirograph-roulette-poi-ring-webxr",
    title: data.title,
    lede: data.lede,
    date: data.date,
    tags: ["blender", "scripting", "geometry", "animation", "webxr"],
    body: Body,
  },
  data,
);
