/**
 * tests/e2e/routes.mjs — Curated route list for the E2E sweep.
 *
 * Top-level public surfaces + key dynamic routes. Pages requiring
 * auth (admin/*, signin/callback) are skipped. Parameterised routes
 * with no seeded data ([slug] without a known fixture) are skipped.
 *
 * To add a route: append { path, slug } below. Slug is used as the
 * screenshot filename, so keep it filesystem-safe (lowercase,
 * hyphen-separated).
 */

export const ROUTES = [
  { path: "/", slug: "home" },
  { path: "/edit", slug: "edit" },
  { path: "/stage", slug: "stage" },
  { path: "/studio", slug: "studio-sanity" },
  { path: "/holo-walk", slug: "holo-walk" },
  { path: "/journal", slug: "journal" },
  { path: "/articles", slug: "articles" },
  { path: "/tutorials", slug: "tutorials" },
  { path: "/aerial", slug: "aerial" },
  { path: "/contact", slug: "contact" },
  { path: "/about", slug: "about" },
  { path: "/sphere", slug: "sphere" },
  { path: "/the-loop", slug: "the-loop" },
  { path: "/services", slug: "services" },
  { path: "/services/looking-glass-quilts", slug: "services-looking-glass-quilts" },
  { path: "/bureau", slug: "bureau" },
  { path: "/bezel", slug: "bezel" },
  { path: "/watch", slug: "watch" },
  { path: "/atelier", slug: "atelier" },
  { path: "/atelier/algorithms", slug: "atelier-algorithms" },
  { path: "/atelier/evolution", slug: "atelier-evolution" },
  { path: "/atelier/poi-sculptor", slug: "atelier-poi-sculptor" },
  { path: "/atelier/shape-of-it", slug: "atelier-shape-of-it" },
  { path: "/atelier/aura-tron", slug: "atelier-aura-tron" },
  { path: "/atelier/procedural-city", slug: "atelier-procedural-city" },
  { path: "/atelier/rig-simulator", slug: "atelier-rig-simulator" },
  { path: "/atelier/cctv-cross-reference", slug: "atelier-cctv-cross-reference" },
  { path: "/atelier/waveguide-forge", slug: "atelier-waveguide-forge" },
  { path: "/atelier/mesh-studio", slug: "atelier-mesh-studio" },
  { path: "/atelier/pattern-prototype", slug: "atelier-pattern-prototype" },
  { path: "/atelier/silk-brush", slug: "atelier-silk-brush" },
  { path: "/atelier/lightpainting-forge", slug: "atelier-lightpainting-forge" },
  { path: "/atelier/quilt-designer", slug: "atelier-quilt-designer" },
  { path: "/atelier/co-drawing", slug: "atelier-co-drawing" },
  { path: "/atelier/cube-composer", slug: "atelier-cube-composer" },
  { path: "/atelier/breeding-floor", slug: "atelier-breeding-floor" },
  { path: "/atelier/dollhouse", slug: "atelier-dollhouse" },
  { path: "/atelier/light-weaver", slug: "atelier-light-weaver" },
  { path: "/atelier/sculpture-gallery", slug: "atelier-sculpture-gallery" },
  { path: "/atelier/modal-lattice", slug: "atelier-modal-lattice" },
  { path: "/atelier/clothing-reverse", slug: "atelier-clothing-reverse" },
  { path: "/atelier/comfy-layered", slug: "atelier-comfy-layered" },
  { path: "/atelier/sprite-designer", slug: "atelier-sprite-designer" },
  { path: "/atelier/triposr", slug: "atelier-triposr" },
  { path: "/visualiser", slug: "visualiser" },
  { path: "/visualiser/total-internal-reflection", slug: "visualiser-tir" },
  { path: "/visualiser/marching-cubes", slug: "visualiser-marching-cubes" },
  { path: "/visualiser/laban-dial", slug: "visualiser-laban-dial" },
  { path: "/visualiser/strange-attractor", slug: "visualiser-strange-attractor" },
  { path: "/visualiser/reaction-diffusion", slug: "visualiser-reaction-diffusion" },
  { path: "/visualiser/caustic-projector", slug: "visualiser-caustic-projector" },
  { path: "/chrono-protocol", slug: "chrono-protocol" },
  { path: "/chrono-protocol/hub", slug: "chrono-protocol-hub" },
  { path: "/chrono-protocol/creative", slug: "chrono-protocol-creative" },
  { path: "/chrono-protocol/run", slug: "chrono-protocol-run" },
  { path: "/play", slug: "play" },
  { path: "/play/neo-london", slug: "play-neo-london" },
  { path: "/practice", slug: "practice" },
  { path: "/rookery", slug: "rookery" },
  { path: "/rookery/about", slug: "rookery-about" },
  { path: "/rookery/tiers", slug: "rookery-tiers" },
  { path: "/rookery/new", slug: "rookery-new" },
  { path: "/stack", slug: "stack" },
  { path: "/pipelines", slug: "pipelines" },
  { path: "/apps", slug: "apps" },
  { path: "/docs", slug: "docs" },
  { path: "/productions", slug: "productions" },
  { path: "/cast", slug: "cast" },
  { path: "/codex", slug: "codex" },
  { path: "/capabilities", slug: "capabilities" },
  { path: "/cards", slug: "cards" },
  { path: "/cards/design", slug: "cards-design" },
  { path: "/cards/mine", slug: "cards-mine" },
  { path: "/wallet", slug: "wallet" },
  { path: "/photographs", slug: "photographs" },
  { path: "/photographs/spatial", slug: "photographs-spatial" },
  { path: "/spatial", slug: "spatial" },
  { path: "/spatial/video", slug: "spatial-video" },
  { path: "/aura/web-llm", slug: "aura-web-llm" },
  { path: "/search", slug: "search" },
  { path: "/search/ask", slug: "search-ask" },
  { path: "/research/cctv-3d-archive", slug: "research-cctv-3d-archive" },
  { path: "/policies", slug: "policies" },
  { path: "/policies/privacy", slug: "policies-privacy" },
  { path: "/policies/terms", slug: "policies-terms" },
  { path: "/policies/print-bureau-terms", slug: "policies-print-bureau" },
  { path: "/signin", slug: "signin" },
  { path: "/learn", slug: "learn" },
  { path: "/demo", slug: "demo" },
  { path: "/demo/vrm", slug: "demo-vrm" },
  { path: "/demo/aura-talks", slug: "demo-aura-talks" },
  { path: "/demo/evolution", slug: "demo-evolution" },
  { path: "/demo/cast-banter", slug: "demo-cast-banter" },
  { path: "/demo/parallax-shells", slug: "demo-parallax-shells" },
];
