/**
 * lib/atelier/comfy-job-response.ts — Shared response shape for the
 * two atelier routes that wrap `viz.generate-comfyui` and return a
 * generated raster artefact.
 *
 * # Used by
 *
 *   - app/api/atelier/pattern-prototype/generate-textile/route.ts
 *   - app/api/atelier/cube-composer/generate-panorama/route.ts
 *
 * Both routes have identical success-response shapes (the call
 * arguments differ — workflow name, prompt — but the result is
 * always { url, bytes, generatedAt, durationMs }). The shape was
 * previously duplicated inline in each route + assumed structurally
 * by the chamber clients. Pinning it here means a schema drift
 * (e.g. adding `meta` to the response) is a single edit + a
 * downstream type-check pass surfaces every caller that needs to
 * adapt.
 *
 * # Error shape
 *
 * Errors are shared with the broader atelier `parseAtelierErrorResponse`
 * helper (lib/atelier/parse-error-response.ts) — the routes emit the
 * same `{ error, code }` envelope on failure, with codes drawn from
 * `ComfyUIGenerateError["code"]` plus `"generation-failed"` for
 * unknown errors.
 */

export type AtelierComfyJobResponse = {
  /** Absolute URL to the generated raster (Vercel Blob). */
  url: string;
  /** Size of the generated bytes on disk — useful for surface UI. */
  bytes: number;
  /** ISO-8601 timestamp the route emitted on success. */
  generatedAt: string;
  /** Wall-clock time the bench + upload took, including queue, in ms. */
  durationMs: number;
};
