/**
 * Neo-London — the data model.
 *
 * Splats are gaussian-splat reconstructions of London locations
 * generated by Apple&rsquo;s SHARP model (open-sourced December 2025).
 * The studio runs SHARP locally on its bench; this site is the
 * destination that catches the output. Each splat gets pinned to the
 * map at the latitude and longitude of its source frame, and once the
 * .ply file lands under /public/splats/ the zone&rsquo;s page renders
 * the splat in three dimensions.
 *
 * The source pool is two-headed: the studio&rsquo;s own ten-year 360
 * walking archive (her own routes, named in
 * /articles/london-360-walking) and London CCTV grabs (TFL JamCams and
 * other public feeds). The CCTV side carries the obvious political
 * shape; the 360 side carries the personal one. Both end up as the
 * same data shape here.
 */

export type SplatSource =
  | "archive-360"
  | "cctv-tfl"
  | "cctv-other"
  | "manual";

export type SplatStatus =
  | "placeholder"
  | "frame-captured"
  | "splat-rendered"
  | "mesh-added"
  | "playable";

export type SplatZone = {
  /** Stable slug for the URL: /play/neo-london/zone/{slug} */
  slug: string;
  /** Display name */
  name: string;
  /** WGS84 latitude */
  lat: number;
  /** WGS84 longitude */
  lng: number;
  /** Where the source frame came from */
  source: SplatSource;
  /** Optional: source-frame URL (public link, or local path documented in docs) */
  sourceFrame?: string;
  /** Path under /public/ for the .ply splat file; null if not yet rendered */
  plyUrl: string | null;
  /** Optional companion mesh GLB (for collision once gameplay lands) */
  meshUrl?: string;
  /** When the source frame was captured (ISO date) */
  capturedAt: string;
  /** When the splat was generated by SHARP (ISO date) */
  splatGeneratedAt?: string;
  /** SHARP model version used */
  sharpVersion?: string;
  /** Notes &mdash; one sentence on what the zone is and why it&rsquo;s interesting */
  notes: string;
  /** Status &mdash; controls how the map pin renders */
  status: SplatStatus;
};
