export default function AddressableLeds() {
  return (
    <>
      <p>
        An addressable LED is an RGB LED package that contains its
        own colour driver and a serial-protocol interface, allowing a
        microcontroller to set each LED&rsquo;s colour independently
        via a single data line (or two, for clocked variants). The
        practical effect: a chain of hundreds of LEDs needs three
        wires from the controller (data, clock if SPI, and ground),
        not three hundred.<sup>1</sup>
      </p>
      <p>
        The two families that dominate hobbyist + studio rig work:
      </p>
      <ul className="ml-6 list-disc space-y-2">
        <li>
          <strong>WS2812 / WS2812B / SK6812 (&ldquo;NeoPixel&rdquo;).</strong>{" "}
          Single-wire timing-sensitive protocol at 800kHz. Cheap,
          ubiquitous, easy. Limitations: the timing constraint means
          interrupts (e.g. for SD card I/O) can corrupt frames if not
          managed; some clones have non-spec-compliant timing windows.
        </li>
        <li>
          <strong>APA102 / SK9822 (&ldquo;DotStar&rdquo;).</strong>{" "}
          Two-wire SPI protocol, clock-driven. Higher refresh rates
          (limited only by SPI clock, not by protocol timing), better
          interrupt tolerance, slightly brighter for the same drive
          current. More expensive per LED. The studio&rsquo;s choice
          for any rig where SD card reading happens during exposure.
        </li>
      </ul>
      <p>
        For light-painting work specifically, three practical concerns
        outweigh raw spec-sheet comparisons:
      </p>
      <ul className="ml-6 list-disc space-y-2">
        <li>
          <strong>Refresh rate.</strong> A rig spinning at 5
          revolutions per second with 200 vertical pixels needs a
          frame update every (1/5)/200 = 1ms. APA102 at 8MHz SPI
          handles this with headroom; WS2812 at 800kHz can keep up
          for short strips but starts choking on long ones.
        </li>
        <li>
          <strong>Colour calibration.</strong> Both families ship
          with stated tolerances on colour temperature and brightness
          per-LED. In practice, individual LEDs in a strip can vary
          by ~5% in white-balance and brightness. The studio applies
          a per-LED correction table loaded onto the rig&rsquo;s SD
          card to flatten the variation.<sup>2</sup>
        </li>
        <li>
          <strong>Power.</strong> A 200-LED strip at full white draws
          up to 12A at 5V (60W). Battery sizing matters; a too-small
          battery sags voltage, which the LED drivers compensate for
          by reducing brightness, producing a visible dimming over
          the exposure. The studio runs oversized LiPo packs to keep
          voltage rail-stiff throughout a 5-minute exposure.
        </li>
      </ul>
      <p>
        Holo-Flow Studio rigs run APA102 strips at 144 LEDs per metre
        density, in single lines of 200 LEDs (for handheld walks) or
        bent into ring configurations (for rotational rigs). Driven by
        a{" "}
        <strong>
          <a
            href="/codex/teensy"
            className="text-pink-200 underline underline-offset-4"
          >
            Teensy
          </a>
        </strong>{" "}
        via hardware SPI; constant-current regulated through a TLC5927
        when peak brightness matters more than control simplicity. See{" "}
        <strong>
          <a
            href="/codex/pov-led-array"
            className="text-pink-200 underline underline-offset-4"
          >
            POV LED array
          </a>
        </strong>{" "}
        for the whole-instrument architecture.<sup>3</sup>
      </p>

      <hr className="my-12 border-warm-black-800" />
      <ol className="ml-6 list-decimal space-y-2 text-sm text-chrome-400">
        <li>
          The chain topology is the substrate&rsquo;s genius. Each
          LED&rsquo;s data-out connects to the next LED&rsquo;s
          data-in; the controller pushes (LED count &times; 3 bytes)
          + a stop frame down the line and the LEDs internally
          forward each subsequent byte. A 200-LED string is one
          data-bus, one ground, one power rail.
        </li>
        <li>
          The correction is generated by photographing a flat white
          test target with the strip lit at known-equal drive values,
          measuring per-pixel deviation in Lightroom, and writing the
          inverse correction back to an SD-card LUT. Done once per
          rig per LED batch; the result is a strip that prints as
          uniformly white across its length, which the camera then
          reads as a clean trace.
        </li>
        <li>
          The TLC5927 constant-current driver sits between the
          controller&rsquo;s LED-protocol output and the LED rail,
          regulating drive current per-channel to within 1% of a
          reference. The result on long exposures is shadows that
          stay neutral and highlights that stay saturated, instead
          of drifting toward magenta or yellow as the battery sags.
        </li>
      </ol>
    </>
  );
}
