/**
 * lib/capabilities/media/library-types.ts — Media library type surface.
 *
 * One Media record per piece of operator-uploaded content (photograph,
 * video, 360 pano, etc.). The record is the system of record; the file
 * itself lives in Vercel Blob, and the metadata in Firestore. Other
 * sources (Google Photos Picker, Google Drive, Sanity) all import INTO
 * this same shape — once imported, the rest of the site doesn't care
 * where it originally came from.
 *
 * Pure types + zod-style runtime narrows in this module. No imports of
 * server packages here, so this module can be referenced from both
 * client and server.
 */

export type MediaKind =
  /** Single still image (JPEG, PNG, AVIF, WebP). */
  | "photo"
  /** Single-exposure light painting — same as photo but flagged. */
  | "photo-single-exposure"
  /** Looped video clip (MP4 / WebM / MOV). */
  | "video"
  /** Equirectangular 360° still photo. */
  | "360-photo"
  /** Equirectangular 360° video. */
  | "360-video"
  /** Side-by-side stereo MP4 (the spatial-video output). */
  | "sbs-stereo-mp4"
  /** USDZ spatial photo for Apple Vision / iOS AR Quick Look. */
  | "usdz"
  /** GLB mesh (InstantMesh / SHARP output). */
  | "glb"
  /** PLY point cloud / Gaussian splat. */
  | "ply"
  /** Audio (WAV / MP3 / OPUS / FLAC). */
  | "audio"
  /** PDF (proofs, contact sheets, certificates). */
  | "pdf"
  /** QR code image (PNG) — generated by viz.splat-ar-deploy. */
  | "qr"
  /** Fallback for kinds the system doesn't enumerate yet. */
  | "other";

export type MediaSource =
  /** Uploaded directly through the admin UI; lives in Vercel Blob. */
  | "vercel-blob"
  /** Imported via the Google Photos Picker; downloaded into Blob. */
  | "google-photos"
  /** Imported via Google Drive; downloaded into Blob. */
  | "google-drive"
  /** Authored in Sanity Studio; URL resolves to Sanity's CDN. */
  | "sanity"
  /** Committed under `public/` in the repo; URL is the static path. */
  | "public-static";

/**
 * Subject of the media — which surface of the site this belongs to.
 * Determines the listing UI and the route the media appears on. Free-
 * form `tag[]` lives on the record itself for finer slicing.
 */
export type MediaSubject =
  | "photograph"
  | "aerial"
  | "holo-walk"
  | "codex"
  | "article"
  | "journal"
  | "tutorial"
  | "product"
  | "rookery"
  | "press"
  | "research"
  | "deploy"
  | "thumbnail"
  | "other";

/** Variant sizes generated at (or after) upload. */
export type MediaVariants = {
  thumbnail?: string;
  small?: string;
  medium?: string;
  large?: string;
  /** Always present; the canonical original URL. */
  original: string;
};

/** Source-specific stable references for re-fetching or sync. */
export type MediaSourceRef = {
  blob?: { pathname: string };
  googlePhotos?: { mediaItemId: string };
  googleDrive?: { fileId: string };
  sanity?: { documentId: string };
  /**
   * Splat-specific metadata. Present when `kind === "ply"` and the file
   * is a 3D Gaussian Splat produced by `viz.splat-generate`. The
   * `licence` field gates commerce surfaces (see `isSplatCommerceEligible`
   * in `lib/capabilities/viz/splat-generate.ts`).
   */
  splat?: {
    /** Keep in sync with `SplatProvider` in
     *  `lib/capabilities/viz/splat-generate.ts`. Widened when the
     *  splat ladder gained `hangar-gsplat` (pinhole video → 3D splat),
     *  `hangar-4dgs` (monocular video → 4D dynamic splat), and
     *  `hangar-compose` (multi-splat stitching). */
    provider:
      | "sharp-onnx"
      | "postshot"
      | "studio-rig-native"
      | "luma-genie"
      | "hangar-gsplat"
      | "hangar-4dgs"
      | "hangar-compose";
    licence:
      | "research-only"
      | "commercial-ok"
      | "third-party-commercial";
    /** Keep in sync with `SplatPlyFlavour` in splat-generate.ts. */
    plyFlavour:
      | "standard-3dgs"
      | "sharp-onnx-raw"
      | "4dgs-deformable-mlp"
      | "4dgs-canonical-time";
    gaussianCount: number;
    sourceImageUrl?: string;
    durationSeconds?: number | null;
  };
  /**
   * Deploy metadata — the AR-deploy capability writes these alongside
   * a QR-code asset that, when scanned, lands the visitor at the
   * deploy URL. `recordId` points back at the source splat record.
   */
  deploy?: {
    recordId: string;
    deployUrl: string;
    qrSizeCm?: number;
  };
  /**
   * Thumbnail-of-a-splat metadata. Present when the media is a poster
   * card or rendered preview for a `SplatRecord` / `Splat360Record`
   * produced by `viz.thumbnail-splat`. The `recordId` points back at
   * the source splat; `provider` records which thumbnail path drew it
   * (the fast card vs the real WebGL screenshot).
   */
  thumbnailSplat?: {
    recordId: string;
    provider: "card-fast" | "splat-real";
  };
  /**
   * ComfyUI-specific metadata. Present when the media was produced by
   * `viz.generate-comfyui`. The workflow + seed pair is the closest thing
   * to a reproducibility key — the bench can rerun the same generation
   * given the workflow JSON + prompt + seed + params.
   */
  comfyui?: {
    workflow:
      | "flux1-dev-fp8"
      | "wan-t2v-1_3b"
      | "hunyuan3d-2mv-turbo"
      | "sdxl-360-panorama"
      | "flux-equirect-lora-v3";
    promptId: string;
    seed?: number;
    prompt: string;
    negativePrompt?: string;
    durationSeconds?: number | null;
  };
};

export type MediaLocation = {
  /** Optional slug linking to a HoloWalk / shoot / venue. */
  slug?: string;
  lat?: number;
  lng?: number;
  name?: string;
};

export type Media = {
  /** Stable id — used in URLs and Firestore doc id. */
  id: string;
  kind: MediaKind;
  subject: MediaSubject;
  source: MediaSource;
  /** Canonical reachable URL; what `<img src=…>` would use. */
  url: string;
  title?: string;
  description?: string;
  /** ISO date — when the media was captured (not uploaded). */
  capturedAt?: string;
  /** ISO date — when the record was created. */
  uploadedAt: string;
  /** Firebase auth uid of the operator who uploaded it. */
  uploadedBy: string;
  /** Pixel dimensions for images / videos. */
  width?: number;
  height?: number;
  /** Seconds — for video / audio. */
  durationSeconds?: number;
  mimeType: string;
  sizeBytes?: number;
  /** SHA-256 of the original bytes; used for dedup. */
  sha256?: string;
  /** Free-form tags for filtering. */
  tags?: string[];
  location?: MediaLocation;
  sourceRef?: MediaSourceRef;
  variants?: MediaVariants;
  /** Soft-retire flag — keeps the file but hides from public lists. */
  retired?: boolean;
};

/** Query shape for `media.list`. */
export type MediaQuery = {
  kind?: MediaKind | MediaKind[];
  subject?: MediaSubject | MediaSubject[];
  source?: MediaSource | MediaSource[];
  tag?: string;
  locationSlug?: string;
  uploadedBy?: string;
  /** Include retired items. Default false. */
  includeRetired?: boolean;
  /** Order by uploadedAt desc by default. */
  orderBy?: "uploadedAt" | "capturedAt";
  limit?: number;
  cursor?: string;
};

/** Pagination result. */
export type MediaPage = {
  items: Media[];
  nextCursor?: string;
};

/** Input to `media.upload`. */
export type MediaUploadInput = {
  /** The bytes — `Blob`, `File`, or a `Buffer`-compatible reader. */
  file: Blob | File | ArrayBuffer | Uint8Array;
  /** Original filename — used to derive Blob pathname. */
  filename: string;
  mimeType: string;
  kind: MediaKind;
  subject: MediaSubject;
  uploadedBy: string;
  title?: string;
  description?: string;
  capturedAt?: string;
  tags?: string[];
  location?: MediaLocation;
  /** Source-of-import marker. Defaults to vercel-blob. */
  source?: MediaSource;
  /** Source-specific reference (e.g. originating Google Photos mediaItemId). */
  sourceRef?: MediaSourceRef;
};

/** Stable error class so callers can `instanceof` it. */
export class MediaLibraryError extends Error {
  constructor(
    message: string,
    public code:
      | "not-configured"
      | "not-authenticated"
      | "upload-failed"
      | "metadata-write-failed"
      | "not-found"
      | "import-failed",
  ) {
    super(message);
    this.name = "MediaLibraryError";
  }
}
