"use client";

/**
 * components/three/VRMAvatar.tsx — Renders a VRM handle from the vrm slice into the R3F scene.
 *
 * One-line role: bridge between the headless `vrm` state slice and the R3F scene graph.
 * Full purpose in VRMAvatar.PURPOSE.md.
 */

import { useEffect, useMemo, useState } from "react";
import { useFrame } from "@react-three/fiber";
import type { VRM, VRMHumanBoneName } from "@pixiv/three-vrm";
import { Object3D } from "three";

import { vrmStore, type VRMHandleId } from "lib/state/vrm";
import { loadVRM, unloadVRM, getVRM } from "lib/capabilities/vrm/load";

export type VRMAvatarProps = {
  /** URL to a .vrm file. The component owns the load + unload lifecycle. */
  url: string;
  /** Optional stable ID. Auto-generated by `loadVRM` when omitted. */
  id?: VRMHandleId;
};

export function VRMAvatar({ url, id: idProp }: VRMAvatarProps) {
  const [handleId, setHandleId] = useState<VRMHandleId | null>(null);
  const lookAtTarget = useMemo(() => new Object3D(), []);

  useEffect(() => {
    let cancelled = false;
    let createdId: VRMHandleId | null = null;

    loadVRM({ url, id: idProp })
      .then((res) => {
        if (cancelled) {
          unloadVRM(res.id);
          return;
        }
        createdId = res.id;
        setHandleId(res.id);
      })
      .catch((err) => {
        if (!cancelled) {
          console.error("VRMAvatar: failed to load", url, err);
        }
      });

    return () => {
      cancelled = true;
      if (createdId) unloadVRM(createdId);
    };
  }, [url, idProp]);

  useFrame((_, delta) => {
    if (!handleId) return;
    const vrm = getVRM(handleId);
    if (!vrm) return;

    const state = vrmStore.getState();

    const pose = state.poses[handleId];
    const offset = state.idleOffsets[handleId];
    if (pose && vrm.humanoid) {
      for (const [name, euler] of Object.entries(pose)) {
        const bone = vrm.humanoid.getNormalizedBoneNode(
          name as VRMHumanBoneName,
        );
        if (!bone) continue;
        const off = offset?.[name];
        if (off) {
          bone.rotation.set(
            euler[0] + off[0],
            euler[1] + off[1],
            euler[2] + off[2],
          );
        } else {
          bone.rotation.set(euler[0], euler[1], euler[2]);
        }
      }
    }

    const weights = state.expressions[handleId];
    if (weights && vrm.expressionManager) {
      for (const [name, weight] of Object.entries(weights)) {
        vrm.expressionManager.setValue(name, weight);
      }
    }

    const target = state.lookTargets[handleId];
    if (target && vrm.lookAt) {
      lookAtTarget.position.set(target[0], target[1], target[2]);
      vrm.lookAt.target = lookAtTarget;
    }

    vrm.update(delta);
  });

  const vrm = handleId ? getVRM(handleId) : null;
  if (!vrm) return null;

  return <primitive object={vrm.scene} />;
}
