"""splat360.pipeline.sfm.hloc — Hierarchical-Localization wrapper.

hloc (cvg/Hierarchical-Localization) is MIT-licensed Python that
replaces COLMAP's SIFT + brute-force matching with learned features
(SuperPoint / DISK) and learned matching (SuperGlue / LightGlue),
then hands off to COLMAP's mapper for triangulation + bundle adjust.

Why it matters here: outdoor sculptures often have smooth painted or
metallic surfaces where SIFT finds very few keypoints. SuperPoint
finds 10-100× more on the same image. The splat is then trained on
a much denser sparse model.

## Pipeline (as a Python module, not a CLI binary)

Unlike COLMAP/OpenSfM/AliceVision, hloc has no shipping CLI. It's
imported as a library. This wrapper writes a small driver script
into the work dir and invokes it as a subprocess so we don't
pollute the service's Python env with hloc's CUDA stack.

## Camera-model coverage

Inherits from COLMAP: PINHOLE and OPENCV_FISHEYE. No SPHERICAL.

## Install

  pip install pycolmap
  pip install git+https://github.com/cvg/Hierarchical-Localization.git
  # plus a recent torch with CUDA matching your driver
"""

from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

from .base import ColmapModel, SfmBackend, SfmInput, SfmResult


_DRIVER_TEMPLATE = '''\
"""Generated by splat360.pipeline.sfm.hloc — runs hloc SfM end to end."""
import sys
from pathlib import Path

from hloc import extract_features, match_features, pairs_from_exhaustive, reconstruction

images = Path({images!r})
work   = Path({work!r})
work.mkdir(parents=True, exist_ok=True)

feature_conf  = extract_features.confs["superpoint_aachen"]
matcher_conf  = match_features.confs["superglue"]

# 1. Extract SuperPoint features.
feature_path = extract_features.main(feature_conf, images, work)

# 2. Pairs to match (exhaustive for now; for video derived sets, the
#    orchestrator can pre-supply pairs_from_sequential output).
pair_path = work / "pairs-exhaustive.txt"
pairs_from_exhaustive.main(pair_path, feature_path)

# 3. Match with SuperGlue.
match_path = match_features.main(matcher_conf, pair_path, feature_conf["output"], work)

# 4. Triangulate + bundle adjust via pycolmap.
sparse = work / "sparse"
sparse.mkdir(exist_ok=True)
reconstruction.main(sparse, images, pair_path, feature_path, match_path)

# 5. Convert to TXT for trainer consumption.
import pycolmap
rec = pycolmap.Reconstruction(sparse)
rec.write_text(sparse)

print("hloc done. registered:", len(rec.images))
'''


class Hloc(SfmBackend):
    name = "hloc"
    licence = "MIT"
    _SUPPORTED: frozenset[ColmapModel] = frozenset({"PINHOLE", "OPENCV_FISHEYE"})

    def __init__(self, python_bin: str | None = None) -> None:
        # Defaults to the running interpreter; override to point at a
        # CUDA-equipped env (e.g. a `.venv-hloc/Scripts/python.exe`).
        self._python = python_bin or sys.executable

    def is_available(self) -> bool:
        # Probe by running `python -c "import hloc"`.
        try:
            r = subprocess.run(
                [self._python, "-c", "import hloc"],
                capture_output=True, text=True, check=False, timeout=10,
            )
            return r.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def supports(self, model: ColmapModel) -> bool:
        return model in self._SUPPORTED

    def run(self, sfm_input: SfmInput) -> SfmResult:
        if not self.supports(sfm_input.camera_model):
            raise ValueError(
                f"hloc does not support camera model {sfm_input.camera_model}"
            )
        work = sfm_input.work_dir
        work.mkdir(parents=True, exist_ok=True)
        driver = work / "_run_hloc.py"
        driver.write_text(
            _DRIVER_TEMPLATE.format(
                images=str(sfm_input.images_dir),
                work=str(work),
            ),
            encoding="utf-8",
        )

        start = time.monotonic()
        subprocess.run([self._python, str(driver)], check=True)
        runtime = time.monotonic() - start

        sparse = work / "sparse"
        if not sparse.exists():
            raise RuntimeError("hloc driver produced no sparse model")

        from .opensfm import _count_lines_in  # reuse the images.txt counter
        registered = _count_lines_in(sparse / "images.txt", header_only=True)
        return SfmResult(
            backend=self.name,
            sparse_dir=sparse,
            registered_images=registered,
            mean_reprojection_error=float("nan"),
            runtime_seconds=runtime,
            raw_outputs=(driver, sparse),
        )
