import Link from "next/link";

const ext = "underline underline-offset-4 hover:text-pink-200";
const arrow = <span className="ml-0.5 text-chrome-500">&nearr;</span>;

export default function BeltPrintedWallReliefs() {
  return (
    <>
      <p>
        I run a{" "}
        <a
          href="https://www.creality.com/products/creality-cr-30-3d-printer"
          target="_blank"
          rel="noopener noreferrer"
          className={ext}
        >
          Creality CR-30{arrow}
        </a>{" "}
        in the corner of the workshop, tilted at 45 degrees, vomiting
        out continuous fabric-like reliefs of dragon-scale and chain-mail
        patterns. It is the most unglamorous machine on the bench and
        it is the one that pays for the others. This piece is about
        what it does, what it makes, and why the studio runs a
        parametric pattern line at all alongside the figurative
        waveguide sculptures.
      </p>

      <p>
        <strong>What a belt printer is.</strong>
      </p>
      <p>
        A belt printer is an FDM 3D printer with the flat heated bed
        replaced by a moving conveyor belt set at an angle &mdash;
        45&deg; on the CR-30. The hotend lays down plastic on the belt
        the same way any FDM printer does; the difference is that as
        each layer is finished, the belt advances a fraction of a
        millimetre, and the part starts to slide out of the print
        volume diagonally. The Z axis is, in the slogan,{" "}
        <em>infinite</em>: the printer doesn&rsquo;t care how long the
        part is. The CR-30&rsquo;s nominal XY build is 200 &times; 170 mm
        and the third dimension is whatever the belt has the patience
        for. The longest single part I&rsquo;ve run was about 2.4
        metres, end to end, and that was a comfort limit on the
        spool, not the machine.
      </p>
      <p>
        The belt itself is a coated nylon weave. It has just enough
        tooth for PLA to grip during printing and just enough release
        for a finished part to slide off the back when the belt comes
        round the roller. The belt is consumable but cheap and
        replaceable; mine is on its third one, two years in.
      </p>

      <p>
        <strong>What the studio does with it.</strong>
      </p>
      <p>
        The CR-30 produces the studio&rsquo;s wall-relief line:
        parametric patterns extruded as long continuous strips, cut
        on the workbench to fit a specific wall. The patterns are
        written as code rather than drawn. Dragon scale (overlapping
        rounded teardrops, offset row to row); chain mail (interlocked
        oval links printed in-place, hinged); gyroid surfaces (the
        triply-periodic minimal surface from soap films and{" "}
        <a
          href="https://en.wikipedia.org/wiki/Gyroid"
          target="_blank"
          rel="noopener noreferrer"
          className={ext}
        >
          mathematics{arrow}
        </a>
        , sliced thin so a single shell prints as a deeply textured
        relief); honeycomb hex with depth modulation; Voronoi cell
        skins driven by a noise field. Each pattern is a small
        OpenSCAD or Grasshopper file with a handful of parameters:
        scale, density, depth, the seed for the noise. Change the
        seed and the same wall has the same family of marks in a
        different rhythm.
      </p>

      <p>
        <strong>The mathematical-vs-figurative split.</strong>
      </p>
      <p>
        The studio&rsquo;s SLA-resin work &mdash; the desktop
        waveguide sculptures, the{" "}
        <Link
          href="/articles/wall-arrays-geometry-of-rooms"
          className={ext}
        >
          wall arrays
        </Link>
        , the pendants &mdash; is figurative. It starts from a
        photograph of an actual gesture made by a body in a darkened
        studio. The 3D model is reconstructed from a real trace; the
        sculpture is a record of a thing that happened.
      </p>
      <p>
        The belt-printer work is the opposite. Nothing was
        photographed. The pattern is mathematical &mdash; rules
        written down, parameters chosen, geometry generated. The
        relief on the wall could in principle be regenerated by a
        stranger with the same OpenSCAD file. The two lines share a
        workshop and almost nothing else: different machine,
        different material, different intent, different price.
        Holding both is deliberate. The figurative work is the
        practice; the parametric work is the wallpaper.
      </p>

      <p>
        <strong>Economics.</strong>
      </p>
      <p>
        The two lines have inverse cost shapes. A palm-scale SLA
        waveguide sculpture takes around four hours on the resin
        printer, plus wash and cure, plus the embedded acrylic
        waveguide work; it carries the time of the photograph it came
        from and the gesture before that. It&rsquo;s priced for what
        it is &mdash; one of a small edition, slow to make,
        load-bearing on a wall.
      </p>
      <p>
        A belt-printed relief is the opposite economy. The machine
        runs unsupervised; one continuous strip can print for thirty
        hours straight. Throughput is roughly{" "}
        <em>around 30&ndash;40 mm of belt advance per hour</em> at
        standard quality settings &mdash; I haven&rsquo;t timed mine
        properly for every pattern, so take that as the rough
        ballpark, not a spec sheet. A square metre of dragon-scale
        relief is roughly a long weekend on the machine and somewhere
        between 600 g and 1.2 kg of filament, depending on the
        pattern depth. Per square metre, the belt-printer work prices
        in the same range as good handmade wallpaper. The lit SLA
        pieces price in the range of a small painting. They are
        different products for different walls and different budgets.
      </p>

      <p>
        <strong>Materials.</strong>
      </p>
      <p>
        The studio default is PLA. PLA prints fast, prints clean, and
        the relief patterns don&rsquo;t need the heat or impact
        resistance you&rsquo;d ask of a functional part. Specifically
        a matte PLA &mdash; the matte finish hides layer lines almost
        completely under normal room light and reads as a textile
        rather than a 3D print. The studio stocks black, bone, slate,
        and a warm rust; commission colours are easy enough to order
        in.
      </p>
      <p>
        PETG goes on the machine when the relief is heading into a
        kitchen or a bathroom &mdash; anywhere with humidity or
        heat. PETG holds up where PLA would slump over a long summer.
        ABS exists on the materials shelf but I rarely run it on the
        belt; the warping fight isn&rsquo;t worth it for relief work.
      </p>
      <p>
        TPU is the interesting one. Flexible TPU on the belt produces
        a relief that drapes. A chain-mail pattern in TPU behaves
        like actual mail &mdash; it folds, it falls over an edge, it
        rolls up for transport. That opens a door the rigid materials
        can&rsquo;t: wall-hung textile rather than wall-fixed panel.
        Commission only, and slow &mdash; TPU prints around half the
        speed of PLA on the belt, in my hands &mdash; but the
        finished thing is genuinely fabric-adjacent.
      </p>

      <p>
        <strong>Aesthetic register.</strong>
      </p>
      <p>
        The lit waveguide sculptures are gallery objects. They have a
        plinth attitude even when mounted on a wall: discrete,
        precious, each one a record of a specific gesture, the room
        arranged around them. The belt-printed reliefs are not that.
        They are domestic-architectural. They want to be a wall, or
        most of a wall, or the back of an alcove, or the run behind a
        bed. They sit closer to{" "}
        <a
          href="https://en.wikipedia.org/wiki/Bas-relief"
          target="_blank"
          rel="noopener noreferrer"
          className={ext}
        >
          bas-relief{arrow}
        </a>{" "}
        and to good wallpaper than they sit to sculpture.
      </p>
      <p>
        I describe them as fabric-like on purpose. The strip comes
        off the belt in continuous metres; you cut it to length the
        way you cut wallpaper or fabric; you butt-join two strips at
        a corner the way you butt-join cloth. The hanging system is
        a slim aluminium top rail with a recess the strip clips into,
        and a matching bottom rail with no fixing &mdash; the strip
        hangs from the top and rests against the bottom. Removable,
        replaceable, re-cuttable. Walls change; this should be able
        to change with them.
      </p>

      <p>
        <strong>Where this sits next to the rest of the studio.</strong>
      </p>
      <p>
        The studio has two output lines that share the same workshop
        and almost no parts. The{" "}
        <Link
          href="/articles/wall-arrays-geometry-of-rooms"
          className={ext}
        >
          wall arrays
        </Link>{" "}
        are palm-scale, lit, figurative, SLA-printed from a
        photograph of a real gesture, priced as art. The belt-printed
        reliefs are large-format, unlit, parametric, FDM-printed from
        a code file, priced as architectural finish. Same studio,
        same person, two registers. The belt printer pays the rent
        while the resin printer makes the work the studio is really
        about. That is fine; that is how most workshops actually
        function.
      </p>
      <p>
        Commissions are open. Send a wall, a length, a pattern
        family, a colour, and the room the wall is in, via the{" "}
        <Link href="/contact?intent=commission" className={ext}>
          contact form
        </Link>
        . If you want to specify the seed you can; if you don&rsquo;t,
        the studio picks one and tells you which.
      </p>
    </>
  );
}
